//! # covex-games-onchain: RISC0->Groth16 receipt -> Kaspa KIP-16 `OpZkPrecompile` (tag 0x20) witness
//!
//! Stage 2 of `docs/ZK_ONCHAIN_PLAN.md`. Once the host produces a real RISC0->Groth16 receipt
//! (`ProverOpts::groth16()`), the settlement covenant must verify it ON-CHAIN via the Kaspa
//! `OpZkPrecompile` opcode (`0xa6`), tag `0x20` (BN254 Groth16). The opcode is a GENERIC
//! ark-groth16 verifier: it pops a verifying key, a proof, an input count, and N field elements,
//! then runs `verify_proof_with_prepared_inputs`. It is NOT RISC0-aware. So the binding to "this
//! exact guest image + this exact journal" has to live in the GROTH16 PUBLIC INPUTS we feed it.
//!
//! ## The RISC0-Groth16 public-input schema (the load-bearing fact)
//!
//! A RISC0 Groth16 receipt verifies against EXACTLY FIVE BN254 `Fr` public inputs, in this order
//! (confirmed against `risc0_groth16::Verifier::new`, risc0-groth16 3.0.4):
//!
//! ```text
//!   [ a0, a1, c0, c1, id_bn254_fr ]
//!     a0,a1        = split_digest(control_root)        // RISC0 recursion control root (version const)
//!     c0,c1        = split_digest(claim_digest)        // SHA-256 digest of the ReceiptClaim
//!     id_bn254_fr  = fr(reverse_bytes(bn254_control_id))// BN254/Poseidon control id (version const)
//! ```
//!
//! `split_digest(d)` reverses `d` to big-endian, splits the 32 bytes in half, and turns each
//! 16-byte half into an `Fr` (so each of a0/a1/c0/c1 is a 128-bit value). The IMAGE ID and the
//! JOURNAL are NOT direct public inputs: they are folded into `claim_digest`. The RISC0
//! `ReceiptClaim` is `{ pre: image_id, post: {pc:0,...}, exit_code: Halted(0), input: ZERO,
//! output: { journal_digest, assumptions: ZERO } }`; its SHA-256 digest is `claim_digest`, and
//! `c0||c1` are that digest split. So:
//!   - a spender CANNOT change the guest program: a different image id changes `pre`, changes the
//!     claim digest, changes c0/c1, and the pinned VK no longer verifies (control root + the
//!     groth16 relation bind image -> claim).
//!   - a spender CANNOT change the journal (winner_pubkey / covenant_id / stake): the journal
//!     digest is inside `output`, inside the claim, inside c0/c1.
//!
//! ## Covenant binding (Stage 3 will enforce this)
//!
//! Because the precompile takes the VK + inputs OFF THE STACK, the SETTLEMENT SCRIPT must bake the
//! VK, a0, a1, and id_bn254_fr as exact-data pushes (a spender cannot swap them), and must bind
//! c0/c1 to the specific covenant. The honest binding to "this pot, this winner" is therefore: the
//! covenant pins `winner_pubkey`/`covenant_id` by REQUIRING the claim digest (c0/c1) that
//! corresponds to a journal with those exact fields. Stage 3 fixes the precise script; this crate
//! just emits the bytes deterministically so Stage 3 + Stage 4 consume identical material.
//!
//! ## What this crate does NOT do
//!
//! It does not itself verify the Groth16 relation (the on-chain node does that), and it does not
//! prove anything (the host does that, needs Docker). It is a pure, deterministic SERIALIZER from a
//! real receipt to on-chain bytes, plus the frozen version constants.

use ark_bn254::{Bn254, Fr, G1Affine, G2Affine};
use ark_ff::PrimeField;
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};
use risc0_zkvm::sha::Digestible;
use risc0_zkvm::{Groth16Receipt, Groth16ReceiptVerifierParameters, ReceiptClaim};

/// The FROZEN Covex games guest image id (`[u32; 8]`). This is the ONE shared multi-game image:
/// every game (chess/connect4/.../poker) is replayed by the same guest, so a single image id + a
/// single VK serve all games. Pinning it in the covenant means a guest upgrade requires a covenant
/// redeploy (documented residual trust, Stage 5).
///
/// It is frozen as a LITERAL here (not re-exported from `methods`) so this crate does not drag the
/// risc0-build guest compile into every consumer. The value was generated by
/// `risc0_build::embed_methods()` from the Stage-1 guest at master 5ca0ffa4. The
/// `image_id_matches_methods` dev-test re-derives it from the live guest and asserts equality, so
/// any drift in the guest source fails the test (re-freeze the constant when that happens).
pub const GAMES_GUEST_ID: [u32; 8] = [
    496092535, 195191819, 3365918585, 3877556533, 1750049808, 219838195, 1454856474, 2517526821,
];

/// The number of BN254 `Fr` public inputs a RISC0 Groth16 receipt verifies against. Always 5
/// (control-root halves a0/a1, claim-digest halves c0/c1, and the bn254 control id).
pub const N_PUBLIC_INPUTS: usize = 5;

/// The on-chain-ready material for one game's settlement spend, all byte-exact for KIP-16 tag 0x20.
#[derive(Clone, Debug)]
pub struct OnchainGroth16 {
    /// ark-serialize **compressed** `VerifyingKey<Bn254>`. Pinned in the locking script.
    pub vk_compressed: Vec<u8>,
    /// ark-serialize **compressed** `Proof<Bn254>` (rebuilt from the RISC0 seal). From the witness.
    pub proof_compressed: Vec<u8>,
    /// The 5 public inputs, each a 32-byte **little-endian** canonical `Fr` (ABI order a0,a1,c0,c1,id).
    pub public_inputs_le: [[u8; 32]; N_PUBLIC_INPUTS],
    /// The raw RISC0 journal bytes (the two-frame GameResult+SettlementJournal). Carried for the
    /// off-chain decoder; the on-chain binding is via the claim digest in c0/c1, not these bytes.
    pub journal: Vec<u8>,
}

/// Error type for the on-chain conversion.
#[derive(Debug)]
pub enum Error {
    /// The receipt is not a Groth16 receipt (e.g. a STARK/composite receipt was passed).
    NotGroth16,
    /// The RISC0 seal could not be parsed into a BN254 proof.
    Seal(String),
    /// ark serialization failed.
    Serialize(String),
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Error::NotGroth16 => write!(f, "receipt is not a Groth16 receipt"),
            Error::Seal(e) => write!(f, "seal parse error: {e}"),
            Error::Serialize(e) => write!(f, "ark serialize error: {e}"),
        }
    }
}
impl std::error::Error for Error {}

/// The default RISC0 Groth16 verifier parameters for the linked risc0-zkvm version: the control
/// root, the bn254 control id, and the Groth16 verifying key. These are CONSTANTS of the RISC0
/// version (and the activated kaspad's RISC0 build must match - Stage 6 / mainnet caveat). We read
/// them from the runtime rather than hardcoding so they always track the linked prover.
fn params() -> Groth16ReceiptVerifierParameters {
    Groth16ReceiptVerifierParameters::default()
}

/// The ark-compressed verifying key the on-chain tag-0x20 verifier deserializes. This is the SAME
/// VK `risc0_groth16::verifying_key()` returns (a constant of the RISC0 version), serialized
/// COMPRESSED (the on-chain ABI calls `VerifyingKey::deserialize_compressed`).
pub fn verifying_key_compressed() -> Result<Vec<u8>, Error> {
    let vk = risc0_groth16::verifying_key();
    serialize_vk_compressed(&vk)
}

/// Serialize a `risc0_groth16::VerifyingKey` as ark-COMPRESSED bytes (the on-chain ABI calls
/// `VerifyingKey::deserialize_compressed`).
///
/// The newtype's inner `ark_groth16::VerifyingKey<Bn254>` is `pub(crate)`, but the crate's serde
/// (`serde_ark`) writes it as a single `Vec<u8>` = the ark VK serialized UNCOMPRESSED. So we:
///   1. serde-serialize the risc0 VK to JSON (a transparent newtype -> a JSON array of u8),
///   2. parse that array back to the raw uncompressed ark bytes,
///   3. `deserialize_uncompressed` into `ark_groth16::VerifyingKey<Bn254>`,
///   4. `serialize_compressed`.
/// Compressed and uncompressed ark encodings recover identical curve points, so the on-chain
/// `deserialize_compressed` reconstructs exactly this VK. A round-trip assertion guards step 4.
fn serialize_vk_compressed(vk: &risc0_groth16::VerifyingKey) -> Result<Vec<u8>, Error> {
    // Step 1+2: extract the uncompressed ark bytes the crate's serde_ark wrote.
    let uncompressed_bytes: Vec<u8> =
        serde_json::from_slice(&serde_json::to_vec(vk).map_err(|e| {
            Error::Serialize(format!("vk serde-to-json: {e}"))
        })?)
        .map_err(|e| Error::Serialize(format!("vk json-to-bytes: {e}")))?;

    // Step 3: ark-deserialize uncompressed.
    let ark_vk = ark_groth16::VerifyingKey::<Bn254>::deserialize_uncompressed(&*uncompressed_bytes)
        .map_err(|e| Error::Serialize(format!("vk ark deserialize_uncompressed: {e}")))?;

    // Step 4: re-serialize COMPRESSED.
    let mut compressed = Vec::new();
    ark_vk
        .serialize_compressed(&mut compressed)
        .map_err(|e| Error::Serialize(format!("vk serialize_compressed: {e}")))?;

    // Guard: the compressed bytes must deserialize back to the same VK (the exact on-chain step).
    let back = ark_groth16::VerifyingKey::<Bn254>::deserialize_compressed(&*compressed)
        .map_err(|e| Error::Serialize(format!("vk compressed round-trip: {e}")))?;
    if back != ark_vk {
        return Err(Error::Serialize("vk compressed round-trip mismatch".into()));
    }
    Ok(compressed)
}

/// Rebuild an `ark_groth16::Proof<Bn254>` from a RISC0 Groth16 seal (256 bytes: a=2x32, b=2x2x32,
/// c=2x32, all big-endian uncompressed coordinates) and serialize it COMPRESSED for the on-chain
/// verifier. This mirrors `risc0_groth16::Verifier::new_inner`'s proof reconstruction exactly.
fn proof_compressed_from_seal(seal: &[u8]) -> Result<Vec<u8>, Error> {
    let s = risc0_groth16::Seal::decode(seal).map_err(|e| Error::Seal(e.to_string()))?;
    let a = g1_from_be(&s.a).map_err(Error::Seal)?;
    let b = g2_from_be(&s.b).map_err(Error::Seal)?;
    let c = g1_from_be(&s.c).map_err(Error::Seal)?;
    let proof = ark_groth16::Proof::<Bn254> { a, b, c };
    let mut out = Vec::new();
    proof
        .serialize_compressed(&mut out)
        .map_err(|e| Error::Serialize(e.to_string()))?;
    Ok(out)
}

/// G1 affine from two 32-byte BIG-ENDIAN coordinates `[x, y]`. This MIRRORS
/// `risc0_groth16::g1_from_bytes` byte-for-byte: it builds `x.rev() || y.rev()` (64 bytes, each
/// coordinate reversed big-endian -> little-endian, NO trailing flags byte) and calls
/// `G1Affine::deserialize_uncompressed`. ark packs the infinity/sign flags into the high bits of the
/// last field byte, so the buffer is exactly 2x field size.
fn g1_from_be(elem: &[Vec<u8>]) -> Result<G1Affine, String> {
    if elem.len() != 2 || elem[0].len() != 32 || elem[1].len() != 32 {
        return Err("g1 element must be 2x32 bytes".into());
    }
    let le: Vec<u8> = elem[0]
        .iter()
        .rev()
        .chain(elem[1].iter().rev())
        .cloned()
        .collect();
    G1Affine::deserialize_uncompressed(&*le).map_err(|e| format!("g1: {e}"))
}

/// G2 affine from a `[[x.c1, x.c0], [y.c1, y.c0]]` 2x2x32 BIG-ENDIAN structure. MIRRORS
/// `risc0_groth16::g2_from_bytes` byte-for-byte: it builds
/// `x.c1.rev() || x.c0.rev() || y.c1.rev() || y.c0.rev()` (128 bytes, NO trailing flags byte) and
/// calls `G2Affine::deserialize_uncompressed`. The exact chain order is what makes the recovered
/// point identical to the one the on-chain verifier reconstructs from the same seal.
fn g2_from_be(elem: &[Vec<Vec<u8>>]) -> Result<G2Affine, String> {
    if elem.len() != 2 || elem[0].len() != 2 || elem[1].len() != 2 {
        return Err("g2 element must be 2x2x32 bytes".into());
    }
    let le: Vec<u8> = elem[0][1]
        .iter()
        .rev()
        .chain(elem[0][0].iter().rev())
        .chain(elem[1][1].iter().rev())
        .chain(elem[1][0].iter().rev())
        .cloned()
        .collect();
    G2Affine::deserialize_uncompressed(&*le).map_err(|e| format!("g2: {e}"))
}

/// `split_digest`: reverse the 32-byte digest to big-endian, split in half, and return the two
/// 16-byte halves AS 32-byte little-endian `Fr` encodings, in ABI order (low half first, then high)
/// exactly as `risc0_groth16::split_digest` produces `(a0, a1)`.
fn split_digest_le(digest_le: &[u8; 32]) -> [[u8; 32]; 2] {
    // risc0 split_digest: big_endian = reverse(d); (b, a) = split_at(16); returns (fr(a), fr(b)).
    let mut be = *digest_le;
    be.reverse();
    let (b_half, a_half) = be.split_at(16); // b = first 16 (high), a = last 16 (low)
    [fr_le_from_be_half(a_half), fr_le_from_be_half(b_half)]
}

/// Turn a 16-byte BIG-ENDIAN half into the 32-byte little-endian canonical `Fr` encoding the
/// on-chain verifier deserializes. risc0 `fr_from_bytes` zero-extends the 16-byte value to 32 bytes
/// big-endian, reverses to little-endian, and `Fr::deserialize_uncompressed` reads it. We compute
/// the same `Fr` and emit its canonical little-endian bytes.
fn fr_le_from_be_half(be_half: &[u8]) -> [u8; 32] {
    // The half is a 128-bit big-endian integer; build the Fr from big-endian bytes.
    let fr = Fr::from_be_bytes_mod_order(be_half);
    fr_to_le32(&fr)
}

/// The bn254 control id as an `Fr`, matching `risc0_groth16::Verifier::new`: it reverses the
/// 32-byte control id and builds an `Fr` from the (now big-endian) hex, i.e. the Fr whose value is
/// the integer of the BYTE-REVERSED control id. We return its canonical 32-byte little-endian form.
fn bn254_control_id_fr_le(control_id_le: &[u8; 32]) -> [u8; 32] {
    // new(): `bn254_control_id.as_mut_bytes().reverse(); fr_from_hex_string(hex(reversed))`.
    // fr_from_hex_string -> from_u256_hex -> fr_from_bytes(reverse -> deserialize LE). Net: the Fr
    // value is the big-endian integer of the REVERSED control id == the little-endian integer of the
    // ORIGINAL control id. So: Fr::from_le_bytes_mod_order(control_id_le).
    let fr = Fr::from_le_bytes_mod_order(control_id_le);
    fr_to_le32(&fr)
}

/// Canonical 32-byte little-endian encoding of an `Fr` (what the on-chain `deserialize_uncompressed`
/// expects, and what ark `serialize_compressed`/`serialize_uncompressed` emit for a scalar).
fn fr_to_le32(fr: &Fr) -> [u8; 32] {
    let mut out = Vec::with_capacity(32);
    fr.serialize_uncompressed(&mut out)
        .expect("Fr serializes to 32 LE bytes");
    let mut arr = [0u8; 32];
    arr.copy_from_slice(&out[..32]);
    arr
}

/// Build the 5 ordered Fr public inputs (32-byte LE each) for a receipt's claim digest, using the
/// frozen control root + bn254 control id of the linked RISC0 version. ABI order: a0, a1, c0, c1, id.
pub fn public_inputs_le(claim_digest_le: &[u8; 32]) -> [[u8; 32]; N_PUBLIC_INPUTS] {
    let p = params();
    let control_root_le: [u8; 32] = (*p.control_root.as_bytes())
        .try_into()
        .expect("control root is 32 bytes");
    let bn254_id_le: [u8; 32] = (*p.bn254_control_id.as_bytes())
        .try_into()
        .expect("bn254 control id is 32 bytes");

    let [a0, a1] = split_digest_le(&control_root_le);
    let [c0, c1] = split_digest_le(claim_digest_le);
    let id = bn254_control_id_fr_le(&bn254_id_le);
    [a0, a1, c0, c1, id]
}

/// The full on-chain conversion: from a real RISC0 Groth16 `Receipt` to the byte-exact KIP-16
/// tag-0x20 witness material. Errors if the receipt is not a Groth16 receipt.
pub fn from_receipt(receipt: &risc0_zkvm::Receipt) -> Result<OnchainGroth16, Error> {
    let groth16: &Groth16Receipt<ReceiptClaim> = match &receipt.inner {
        risc0_zkvm::InnerReceipt::Groth16(g) => g,
        _ => return Err(Error::NotGroth16),
    };

    // The claim digest the on-chain inputs bind to: SHA-256 of the (pruned-or-full) ReceiptClaim.
    let claim_digest = groth16.claim.digest();
    let claim_digest_le: [u8; 32] = (*claim_digest.as_bytes())
        .try_into()
        .expect("claim digest is 32 bytes");

    let vk_compressed = verifying_key_compressed()?;
    let proof_compressed = proof_compressed_from_seal(&groth16.seal)?;
    let public_inputs_le = public_inputs_le(&claim_digest_le);

    Ok(OnchainGroth16 {
        vk_compressed,
        proof_compressed,
        public_inputs_le,
        journal: receipt.journal.bytes.clone(),
    })
}

/// Convenience: lowercase hex of a byte slice (for writing the sample artifacts).
pub fn hex_of(bytes: &[u8]) -> String {
    hex::encode(bytes)
}

/// The frozen image id as the canonical lowercase hex string (the RISC0 `[u32;8]` rendered as the
/// 32-byte digest, little-endian within each word as RISC0 stores it). Used for the pinned-constant
/// record in the sample dir.
pub fn image_id_hex() -> String {
    let mut bytes = Vec::with_capacity(32);
    for w in GAMES_GUEST_ID.iter() {
        bytes.extend_from_slice(&w.to_le_bytes());
    }
    hex::encode(bytes)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The frozen `GAMES_GUEST_ID` literal must equal the image id the live guest compiles to. If
    /// the guest source changes, this fails and the literal must be re-frozen (and any deployed
    /// covenant redeployed - the image id is pinned on-chain).
    #[test]
    fn image_id_matches_methods() {
        assert_eq!(
            GAMES_GUEST_ID, methods::GAMES_GUEST_ID,
            "frozen GAMES_GUEST_ID drifted from the compiled guest image id - re-freeze it"
        );
    }

    /// The VK is deterministic and non-empty, and a compressed `VerifyingKey<Bn254>` round-trips
    /// (so the on-chain `deserialize_compressed` will accept it).
    #[test]
    fn vk_compressed_roundtrips() {
        let vk = verifying_key_compressed().expect("vk");
        assert!(!vk.is_empty(), "vk must serialize");
        let back = ark_groth16::VerifyingKey::<Bn254>::deserialize_compressed(&*vk)
            .expect("compressed VK must deserialize (on-chain ABI does exactly this)");
        let mut re = Vec::new();
        back.serialize_compressed(&mut re).unwrap();
        assert_eq!(re, vk, "VK compressed encoding must be canonical/stable");
    }

    /// `public_inputs_le` is deterministic and emits exactly 5 canonical 32-byte LE Fr inputs that
    /// the on-chain `Fr::deserialize_uncompressed` accepts.
    #[test]
    fn public_inputs_are_five_canonical_le_fr() {
        let claim = [0x11u8; 32];
        let inputs = public_inputs_le(&claim);
        assert_eq!(inputs.len(), N_PUBLIC_INPUTS);
        for (i, fr_le) in inputs.iter().enumerate() {
            let fr = Fr::deserialize_uncompressed(&fr_le[..])
                .unwrap_or_else(|e| panic!("input {i} must be a canonical LE Fr: {e}"));
            // round-trip to confirm canonical
            let mut re = Vec::new();
            fr.serialize_uncompressed(&mut re).unwrap();
            assert_eq!(&re[..], &fr_le[..], "input {i} not canonical");
        }
        // Determinism: same claim -> same inputs.
        assert_eq!(inputs, public_inputs_le(&claim));
    }

    /// The control-root halves (a0,a1) and the bn254 id input are FIXED constants of the RISC0
    /// version (independent of the claim), so two different claims share a0/a1/id and differ only in
    /// c0/c1. This is the property Stage 3 relies on (pin a0/a1/id + VK; bind c0/c1 to the journal).
    #[test]
    fn control_inputs_are_claim_independent() {
        let a = public_inputs_le(&[0x01u8; 32]);
        let b = public_inputs_le(&[0x02u8; 32]);
        assert_eq!(a[0], b[0], "a0 (control root low) must be claim-independent");
        assert_eq!(a[1], b[1], "a1 (control root high) must be claim-independent");
        assert_eq!(a[4], b[4], "id_bn254_fr must be claim-independent");
        assert_ne!(a[2], b[2], "c0 must change with the claim digest");
    }

    /// SEAL DECODER CORRECTNESS (no real receipt needed): build a known `Proof<Bn254>`, encode its
    /// points into the RISC0 seal byte format (the inverse of `g1_from_be`/`g2_from_be`), run it
    /// through our `proof_compressed_from_seal`, and assert the recovered proof equals the original.
    /// This proves the G1/G2 coordinate ordering (big-endian, the exact `x.c1,x.c0` G2 chain) is
    /// correct, so the on-chain verifier (which reconstructs from the SAME seal) sees the same points.
    #[test]
    fn seal_decoder_roundtrips_a_known_proof() {
        use ark_bn254::{Fr as ScalarFr, G1Projective, G2Projective};
        use ark_ec::PrimeGroup;

        // A deterministic, non-trivial proof: distinct scalar multiples of the generators.
        let a_pt: G1Affine = (G1Projective::generator() * ScalarFr::from(7u64)).into();
        let b_pt: G2Affine = (G2Projective::generator() * ScalarFr::from(11u64)).into();
        let c_pt: G1Affine = (G1Projective::generator() * ScalarFr::from(13u64)).into();
        let proof = ark_groth16::Proof::<Bn254> { a: a_pt, b: b_pt, c: c_pt };

        // Encode to RISC0 seal bytes: the inverse of g1_from_be/g2_from_be. ark `serialize_uncompressed`
        // writes each Fp little-endian (last byte carries flags; for these non-infinity points the
        // flag bits are 0); we reverse to big-endian and lay out a(2x32) b(2x2x32) c(2x32) = 256 bytes.
        fn g1_to_seal(p: &G1Affine) -> Vec<Vec<u8>> {
            let mut buf = Vec::new();
            p.serialize_uncompressed(&mut buf).unwrap(); // x_le(32) || y_le(32)
            let x: Vec<u8> = buf[0..32].iter().rev().cloned().collect();
            let y: Vec<u8> = buf[32..64].iter().rev().cloned().collect();
            vec![x, y]
        }
        fn g2_to_seal(p: &G2Affine) -> Vec<Vec<Vec<u8>>> {
            let mut buf = Vec::new();
            p.serialize_uncompressed(&mut buf).unwrap(); // x.c0_le, x.c1_le, y.c0_le, y.c1_le
            let xc0: Vec<u8> = buf[0..32].iter().rev().cloned().collect();
            let xc1: Vec<u8> = buf[32..64].iter().rev().cloned().collect();
            let yc0: Vec<u8> = buf[64..96].iter().rev().cloned().collect();
            let yc1: Vec<u8> = buf[96..128].iter().rev().cloned().collect();
            // g2_from_be expects [[x.c1, x.c0], [y.c1, y.c0]] big-endian.
            vec![vec![xc1, xc0], vec![yc1, yc0]]
        }
        let seal_struct = risc0_groth16::Seal {
            a: g1_to_seal(&proof.a),
            b: g2_to_seal(&proof.b),
            c: g1_to_seal(&proof.c),
        };
        let seal_bytes = seal_struct.to_vec();
        assert_eq!(seal_bytes.len(), 256, "RISC0 Groth16 seal is 256 bytes");

        // Run our converter and recover the proof from the compressed bytes.
        let compressed = proof_compressed_from_seal(&seal_bytes).expect("decode seal -> compressed");
        let recovered =
            ark_groth16::Proof::<Bn254>::deserialize_compressed(&*compressed).expect("recover proof");

        assert_eq!(recovered.a, proof.a, "G1 'a' point mismatch (byte ordering wrong)");
        assert_eq!(recovered.b, proof.b, "G2 'b' point mismatch (Fp2/coord ordering wrong)");
        assert_eq!(recovered.c, proof.c, "G1 'c' point mismatch");
    }
}
