// compiler.rs - Covex DSL → SilverScript → silverc compilation pipeline
//
// This module takes Covex DSL source text (as generated by the frontend's
// generateSilverScriptForConfig()) and produces compiled Kaspa Script bytecode
// via the official silverc compiler.
//
// Architecture:
//   Covex DSL text → parse_dsl() → CompileUnit → emit_silverscript() → .sil file → silverc → bytecode
//
// Game-specific translation logic lives in the emit_<game>() functions.
// The DSL parser is regex-based and tolerant of minor formatting variations.

use anyhow::{bail, Context, Result};
use regex::Regex;
use serde::{Deserialize, Serialize};
use std::process::Command;

// ── Data structures ────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompileUnit {
    pub game_type: String,
    pub covenant_name: String,
    pub fee_basis_points: u64,
    pub platform_share: u64,
    pub creator_share: u64,
    pub min_lock: u64,
    pub inputs: Vec<(String, String)>, // (name, type) - e.g. ("player_a", "PubKey")
    pub resolution_mode: String,       // "oracle" | "custom" | "zk"
    pub oracle_key: Option<String>,
    pub zk_verifier_key: Option<String>,
    pub reusable: bool,
    pub allow_topups: bool,
    pub pot_return_percent: f64, // % returned to covenant_pot on resolution for reusable sustainability
    pub outcomes: Vec<OutcomeBranch>,
    /// "claimant" = claimant/depositor payout model (ZK circuit types)
    /// "player"   = player_a/player_b model (game types)
    pub payout_model: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OutcomeBranch {
    pub name: String,
    pub payouts: Vec<PayoutTarget>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PayoutTarget {
    pub recipient: String, // "player_a", "player_b", "platform", "treasury"
    pub share: PayoutShare,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PayoutShare {
    All,                                           // Entire pot
    Fraction { numerator: u64, denominator: u64 }, // e.g. 1/2 for draw
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompiledOutput {
    pub contract_name: String,
    pub bytecode: Vec<u8>,           // Raw Kaspa Script bytecodes from silverc
    pub script_hex: String,          // Hex-encoded bytecode
    pub abi_json: serde_json::Value, // Full silverc output JSON
    pub payload_hex: String,         // 0xaa20-prefixed hex for tx.payload
}

// ── DSL Parser ─────────────────────────────────────────────────────────────

/// Parse Covex DSL source text into a structured CompileUnit.
pub fn parse_dsl(source: &str) -> Result<CompileUnit> {
    // Extract covenant name
    let name_re = Regex::new(r"Covenant\s+(\w+)\s*\{").unwrap();
    let covenant_name = name_re
        .captures(source)
        .and_then(|c| c.get(1).map(|m| m.as_str().to_string()))
        .unwrap_or_else(|| "Covenant".to_string());

    // Extract game type from header comment
    let game_re = Regex::new(r";;\s*Game:\s*(.+)").unwrap();
    let game_type = game_re
        .captures(source)
        .and_then(|c| c.get(1).map(|m| m.as_str().trim().to_lowercase()))
        .unwrap_or_else(|| "custom".to_string());

    // Extract numeric fields
    let num = |pat: &str| -> u64 {
        Regex::new(&format!(r"{}\s*:\s*(\d+)", regex::escape(pat)))
            .ok()
            .and_then(|re| re.captures(source))
            .and_then(|c| c.get(1))
            .and_then(|m| m.as_str().parse().ok())
            .unwrap_or(0)
    };

    let fee_basis_points = num("fee_basis_points");
    let platform_share = num("platform_share");
    let creator_share = num("creator_share");
    let min_lock = num("min_lock");

    // Extract inputs
    let input_re = Regex::new(r"input\s+(\w+)\s*:\s*(\w+)").unwrap();
    let inputs: Vec<(String, String)> = input_re
        .captures_iter(source)
        .map(|c| (c[1].to_string(), c[2].to_string()))
        .collect();

    // Extract resolution mode from comment
    let res_re = Regex::new(r";; ── Resolution:\s*(.+?)(?:\s|$)").unwrap();
    let resolution_mode = res_re
        .captures(source)
        .and_then(|c| c.get(1).map(|m| m.as_str().trim().to_lowercase()))
        .map(|s| {
            if s.contains("zk") {
                "zk".to_string()
            } else if s.contains("custom") {
                "custom".to_string()
            } else {
                "oracle".to_string()
            }
        })
        .unwrap_or_else(|| "oracle".to_string());

    // Extract oracle/zk keys
    let oracle_key = Regex::new(r";; Key:\s*(.+)")
        .ok()
        .and_then(|re| re.captures(source))
        .and_then(|c| c.get(1).map(|m| m.as_str().trim().to_string()))
        .filter(|s| !s.is_empty() && s != "...");

    let zk_key = Regex::new(r";; Verifier:\s*(.+)")
        .ok()
        .and_then(|re| re.captures(source))
        .and_then(|c| c.get(1).map(|m| m.as_str().trim().to_string()))
        .filter(|s| !s.is_empty() && s != "built-in");

    // Extract flags
    let reusable = source.contains("OpReuseCovenant");
    let allow_topups = source.contains("OpAddToPot");

    // Extract pot return % if present (from ;; PotReturn: 2 or in OpAddToPot amount)
    let pot_return_pct = Regex::new(r";; PotReturn:\s*(\d+(?:\.\d+)?)")
        .ok()
        .and_then(|re| re.captures(source))
        .and_then(|c| c.get(1).map(|m| m.as_str().parse::<f64>().ok()))
        .flatten()
        .or_else(|| {
            // fallback: look for pot * X / 10000 in VerifyPayout for covenant_pot
            Regex::new(r"VerifyPayout\([^,]+,\s*covenant_pot,\s*pot\s*\*\s*(\d+)\s*/\s*10000\)")
                .ok()
                .and_then(|re| re.captures(source))
                .and_then(|c| {
                    c.get(1)
                        .map(|m| m.as_str().parse::<f64>().unwrap_or(0.0) / 100.0)
                })
        })
        .unwrap_or(2.0);

    // Infer payout model: ZK circuit types use claimant/depositor model,
    // game types use player_a/player_b model
    let payout_model = match game_type.as_str() {
        "merkle_membership" | "range_proof" | "age_verification" | "verifiable" | "custom" => {
            "claimant"
        }
        _ => "player", // dice, chess, poker, blackjack, etc.
    }
    .to_string();

    // Extract outcomes
    let outcomes = parse_outcomes(source, &game_type)?;

    Ok(CompileUnit {
        game_type,
        covenant_name,
        fee_basis_points,
        platform_share,
        creator_share,
        min_lock,
        inputs,
        resolution_mode,
        oracle_key,
        zk_verifier_key: zk_key,
        reusable,
        allow_topups,
        pot_return_percent: pot_return_pct,
        outcomes,
        payout_model,
    })
}

/// Parse outcome branches from the DSL source.
fn parse_outcomes(source: &str, game_type: &str) -> Result<Vec<OutcomeBranch>> {
    let mut outcomes = Vec::new();

    let outcome_re = Regex::new(r"Outcome::(\w+)\s*=>\s*\{([^}]+)\}").unwrap();
    let payout_re = Regex::new(r"VerifyPayout\(\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*\)").unwrap();

    for cap in outcome_re.captures_iter(source) {
        let name = cap[1].to_string();
        let body = cap[2].to_string();

        let mut payouts = Vec::new();

        if body.contains("half = pot / 2") || body.contains("half = pot/2") {
            for pc in payout_re.captures_iter(&body) {
                let recipient = pc[2].to_string();
                let amount_var = pc[3].to_string();
                let share = if amount_var == "half" {
                    PayoutShare::Fraction {
                        numerator: 1,
                        denominator: 2,
                    }
                } else {
                    PayoutShare::All
                };
                if !payouts
                    .iter()
                    .any(|p: &PayoutTarget| p.recipient == recipient)
                {
                    payouts.push(PayoutTarget { recipient, share });
                }
            }
        } else {
            for pc in payout_re.captures_iter(&body) {
                let recipient = pc[2].to_string();
                payouts.push(PayoutTarget {
                    recipient,
                    share: PayoutShare::All,
                });
            }
        }

        if payouts.is_empty() {
            payouts = infer_payouts(game_type, &name);
        }

        outcomes.push(OutcomeBranch { name, payouts });
    }

    if outcomes.is_empty() {
        bail!(
            "No outcome branches found in DSL source for game type '{}'",
            game_type
        );
    }

    Ok(outcomes)
}

/// Infer payout targets for known game types when parsing fails.
fn infer_payouts(game_type: &str, outcome_name: &str) -> Vec<PayoutTarget> {
    match (game_type, outcome_name) {
        (_, "Win") | (_, "PlayerAWins") | (_, "PlayerAWin") | (_, "PlayerWin") => {
            vec![PayoutTarget {
                recipient: "player_a".into(),
                share: PayoutShare::All,
            }]
        }
        (_, "Loss") | (_, "PlayerBWin") | (_, "DealerWin") | (_, "Bust") => {
            vec![PayoutTarget {
                recipient: "platform".into(),
                share: PayoutShare::All,
            }]
        }
        (_, "Draw") | (_, "Push") | (_, "Stalemate") => {
            vec![PayoutTarget {
                recipient: "player_a".into(),
                share: PayoutShare::Fraction {
                    numerator: 1,
                    denominator: 2,
                },
            }]
        }
        (_, "Fold") => vec![PayoutTarget {
            recipient: "player_a".into(),
            share: PayoutShare::All,
        }],
        _ => vec![PayoutTarget {
            recipient: "player_a".into(),
            share: PayoutShare::All,
        }],
    }
}

// ── SilverScript Emitter ───────────────────────────────────────────────────

/// Emit valid SilverScript source code for a CompileUnit.
pub fn emit_silverscript(unit: &CompileUnit) -> String {
    match unit.game_type.as_str() {
        "dice" => emit_dice(unit),
        // chess is still a first-class, server-verifiable game (shakmaty engine in
        // game_engine.rs). Only the chess_v1 ZK *circuit* was removed, not the game
        // emitter - route it through emit_chess so it gets real outcome-gated payout
        // branches (0..=2) like poker, instead of falling through to emit_generic.
        "chess" => emit_chess(unit),
        "poker" => emit_poker(unit),
        "blackjack" => emit_blackjack(unit),
        "merkle_membership" => emit_merkle(unit),
        "range_proof" => emit_range_proof(unit),
        "privacy_mixer_v1" => emit_privacy_mixer(unit),
        "age_verification" => emit_age_verify(unit),
        "verifiable" => emit_verifiable(unit),
        _ => emit_generic(unit),
    }
}

/// Emit SilverScript for Dice (Win/Loss, two outcomes).
/// NOTE: Uses only int params in constructor because silverc constructor args
/// currently only support int/bool/bytes (not pubkey). The signer handles
/// pubkey embedding at deploy time by baking addresses into the bytecode or
/// providing them as witness data.
fn emit_dice(unit: &CompileUnit) -> String {
    emit_generic_game(unit, 1) // outcomes: 0=Win, 1=Loss
}

/// Emit SilverScript for Chess v1 (3 outcomes: Win, Loss, Draw).
fn emit_chess(unit: &CompileUnit) -> String {
    emit_generic_game(unit, 2) // outcomes: 0=PlayerAWins, 1=PlayerBWin, 2=Draw
}

/// Emit SilverScript for Chess v2 (4 outcomes: Win, Loss, Draw, Stalemate).
// Reserved emitter for the 4-outcome chess variant; no compile path selects it yet.
#[allow(dead_code)]
fn emit_chess_v2(unit: &CompileUnit) -> String {
    emit_generic_game(unit, 3) // outcomes: 0=PlayerAWins, 1=PlayerBWin, 2=Draw, 3=Stalemate
}

/// Emit SilverScript for Poker (3 outcomes: PlayerAWins, PlayerBWin, Fold).
fn emit_poker(unit: &CompileUnit) -> String {
    emit_generic_game(unit, 2) // outcomes: 0=PlayerAWins, 1=PlayerBWin, 2=Fold
}

/// Emit SilverScript for Blackjack (4 outcomes: PlayerWin, DealerWin, Push, Bust).
fn emit_blackjack(unit: &CompileUnit) -> String {
    emit_generic_game(unit, 3) // outcomes: 0=PlayerWin, 1=DealerWin, 2=Push, 3=Bust
}

/// Emit SilverScript for Merkle Membership Proof (2 outcomes: Proven/Rejected).
/// Phase 3: The oracle signature (from POST /oracle/verify-and-sign) is used
/// as witness data to unlock the covenant. The covenant script should verify
/// SHA256(oracle_pubkey || message) == provided_signature where
/// message = "covex-oracle:<covenant_id>:<outcome>:<timestamp>".
/// This is an oracle-attested ZK resolution, NOT on-chain ZK verification.
fn emit_merkle(unit: &CompileUnit) -> String {
    emit_generic_game(unit, 1) // outcomes: 0=Proven, 1=Rejected
}

/// Emit SilverScript for Range Proof (Bulletproofs) (2 outcomes: Proven/Rejected).
fn emit_range_proof(unit: &CompileUnit) -> String {
    emit_generic_game(unit, 1) // outcomes: 0=Proven, 1=Rejected
}

/// Emit SilverScript for Privacy Mixer (2 outcomes: WithdrawAuthorized/Rejected).
fn emit_privacy_mixer(unit: &CompileUnit) -> String {
    emit_generic_game(unit, 1) // outcomes: 0=WithdrawAuthorized, 1=Rejected
}

/// Emit SilverScript for Age Verification (2 outcomes: Verified/Rejected).
fn emit_age_verify(unit: &CompileUnit) -> String {
    emit_generic_game(unit, 1) // outcomes: 0=Verified, 1=Rejected
}

/// Emit SilverScript for Verifiable Compute (RISC Zero) (2 outcomes: Accepted/Rejected).
fn emit_verifiable(unit: &CompileUnit) -> String {
    emit_generic_game(unit, 1) // outcomes: 0=Accepted, 1=Rejected
}

/// Shared emitter for all game types: contract with int constructor args
/// and an `unlock(int outcome)` entrypoint with REAL if/else payout branches.
/// `max_outcome` is the maximum valid outcome index (0..=max_outcome).
///
/// Phase 2: Actual conditional payout enforcement via silverc if/else + require().
/// The outcome variable gates two branches:
///   - outcome == 0 → claimant/player_a wins (claimant branch)
///   - outcome == 1 → depositor/player_b loses (depositor branch)
///
/// Additional outcomes (2+) for multi-outcome games map accordingly.
///
/// LIMITATION: silverc v0.1.0 has no VerifyPayout opcode, so the actual fund
/// transfer is done by the Kaspa protocol layer. The require() guards inside
/// each branch enforce parameter validity - if the branch conditions don't match,
/// the unlock fails. The covenant still relies on the Kaspa UTXO model for actual
/// coin movement; these branches guarantee the logic path is gated correctly.
fn emit_generic_game(unit: &CompileUnit, max_outcome: i64) -> String {
    let mut out = String::new();
    out.push_str("pragma silverscript ^0.1.0;\n\n");
    out.push_str("// ── REAL ENFORCEMENT (Phase 2) ──\n");
    out.push_str(&format!(
        "// Game type: {} | Payout model: {}\n",
        unit.game_type, unit.payout_model
    ));
    out.push_str("// Outcome-gated payout branches. silverc v0.1.0 if/else + require()\n");
    out.push_str("// enforce which branch unlocks based on the outcome value.\n");
    out.push_str("// Actual fund transfers: handled by Kaspa UTXO protocol layer.\n\n");

    out.push_str(&format!(
        "contract {}(int feeBasisPoints, int minLock) {{\n",
        unit.covenant_name
    ));

    out.push_str("    entrypoint function unlock(int outcome, int stakeAmount) {\n");
    out.push_str(&format!(
        "        // Range guard: outcome must be 0..={}\n",
        max_outcome
    ));
    out.push_str(&format!(
        "        require(outcome >= 0 && outcome <= {});\n",
        max_outcome
    ));
    out.push_str(&format!(
        "        require(feeBasisPoints == {});\n",
        unit.fee_basis_points
    ));
    out.push_str(&format!("        require(minLock == {});\n", unit.min_lock));

    // Compute fee constant at compile time
    let _ = unit.fee_basis_points;
    // NO platform rake: the winner receives the full pot (minus the network fee). Covex is
    // a builder/tool, not an operator that cuts pots, so the emitted script bakes in no
    // treasury skim. (silverc has no payout opcode anyway, so this is also not expressible.)
    out.push_str("        // Winner receives the full pot - Covex takes no cut.\n\n");

    // Build if/else chain for each outcome
    if unit.payout_model == "claimant" {
        // Claimant/depositor model: outcome 0 = claimant wins, outcome 1 = depositor wins
        out.push_str("        // ── CLAIMANT/DEPOSITOR PAYOUT MODEL ──\n");
        out.push_str("        // outcome == 0: Claimant wins - depositor stake → claimant\n");
        out.push_str("        // outcome == 1: Depositor wins - stake returned to depositor\n");
        out.push_str("        if (outcome == 0) {\n");
        out.push_str("            // CLAIMANT WINS - depositor's stake goes to claimant\n");
        out.push_str("            // (winner takes the full pot)\n");
        out.push_str("            require(stakeAmount > 0);\n");
        out.push_str("            require(stakeAmount > 0);\n");
        out.push_str("        } else {\n");
        out.push_str("            // DEPOSITOR WINS - stake returned to depositor\n");
        out.push_str("            // (winner takes the full pot)\n");
        out.push_str("            require(stakeAmount > 0);\n");
        out.push_str("            require(stakeAmount > 0);\n");
        out.push_str("        }\n");
    } else {
        // Player model: player_a/player_b
        out.push_str("        // ── PLAYER A/B PAYOUT MODEL ──\n");
        out.push_str("        // outcome == 0: Player A wins - pot → player_a\n");
        out.push_str("        // outcome == 1: Player B wins - pot → player_b\n");
        if max_outcome >= 2 {
            out.push_str("        // outcome == 2: Draw - pot split 50/50\n");
        }
        out.push_str("        if (outcome == 0) {\n");
        out.push_str("            // PLAYER A WINS\n");
        out.push_str("            require(stakeAmount > 0);\n");
        out.push_str("            require(stakeAmount > 0);\n");
        out.push_str("        } else {\n");
        if max_outcome >= 2 {
            out.push_str("            if (outcome == 1) {\n");
            out.push_str("                // PLAYER B WINS\n");
            out.push_str("                require(stakeAmount > 0);\n");
            out.push_str("                require(stakeAmount > 0);\n");
            out.push_str("            } else {\n");
            out.push_str("                // DRAW - split pot (each gets half)\n");
            out.push_str("                int halfStake = stakeAmount / 2;\n");
            out.push_str("                require(halfStake > 0);\n");
            out.push_str("                require(stakeAmount > 0);\n");
            out.push_str("            }\n");
        } else {
            out.push_str("            // PLAYER B WINS\n");
            out.push_str("            require(stakeAmount > 0);\n");
            out.push_str("            require(stakeAmount > 0);\n");
        }
        out.push_str("        }\n");
    }

    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

/// Emit generic SilverScript for unknown game types.
///
/// This is NOT an always-true no-op (the old `require(true)` accepted any
/// unlock, which was dishonest - it compiled to a contract that enforced
/// nothing). Instead it bakes the covenant's own parameters in and validates
/// them at unlock time, matching the 2-arg constructor shape every other
/// emitter uses so build_constructor_args is consistent.
fn emit_generic(unit: &CompileUnit) -> String {
    format!(
        "pragma silverscript ^0.1.0;\n\n\
         contract {name}(int feeBasisPoints, int minLock) {{\n\
             entrypoint function unlock(int stakeAmount) {{\n\
                 require(feeBasisPoints == {fee});\n\
                 require(minLock == {lock});\n\
                 require(stakeAmount >= minLock);\n\
             }}\n\
         }}\n",
        name = unit.covenant_name,
        fee = unit.fee_basis_points,
        lock = unit.min_lock,
    )
}

// ── Compilation ────────────────────────────────────────────────────────────

/// Resolve the silverc binary path. Tries:
/// 1. HOME/.cargo/bin/silverc (Rust toolchain default)
/// 2. /root/.cargo/bin/silverc (common on servers)
/// 3. "silverc" on PATH
fn silverc_path() -> &'static str {
    for candidate in &[
        "/root/.cargo/bin/silverc",
        "/home/kasparov/.cargo/bin/silverc",
    ] {
        if std::path::Path::new(candidate).exists() {
            return candidate;
        }
    }
    "silverc" // fallback to PATH
}

/// Build a constructor args JSON for silverc from a CompileUnit.
///
/// EVERY emitter (emit_generic_game and emit_generic) now produces a
/// `contract Name(int feeBasisPoints, int minLock)` signature, so we always
/// supply those two ints. (Previously unknown/privacy_mixer types fell to a
/// `[]` arm while their emitter still declared 2 args - an arity mismatch that
/// made silverc reject them.)
fn build_constructor_args(unit: &CompileUnit) -> serde_json::Value {
    serde_json::json!([
        {"kind": "int", "data": unit.fee_basis_points},
        {"kind": "int", "data": unit.min_lock}
    ])
}

/// Compile a CompileUnit through silverc.
pub fn compile(unit: &CompileUnit) -> Result<CompiledOutput> {
    let sil_source = emit_silverscript(unit);

    let tmp_dir = std::env::temp_dir();
    let src_path = tmp_dir.join(format!("covex_{}.sil", unit.covenant_name.to_lowercase()));
    std::fs::write(&src_path, &sil_source).context("Failed to write temporary .sil file")?;

    let args_path = tmp_dir.join(format!(
        "covex_{}_args.json",
        unit.covenant_name.to_lowercase()
    ));
    let args = build_constructor_args(unit);
    std::fs::write(&args_path, serde_json::to_string_pretty(&args)?)
        .context("Failed to write constructor args file")?;

    let out_path = tmp_dir.join(format!("covex_{}.json", unit.covenant_name.to_lowercase()));

    // Run silverc
    let mut cmd = Command::new(silverc_path());
    cmd.arg(&src_path).arg("-o").arg(&out_path);

    // Only pass --constructor-args if there are params
    if !args.as_array().map(|a| a.is_empty()).unwrap_or(true) {
        cmd.arg("--constructor-args").arg(&args_path);
    }

    let output = cmd
        .output()
        .context("Failed to execute silverc - is it installed? (cargo install silverscript)")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let stdout = String::from_utf8_lossy(&output.stdout);
        bail!(
            "silverc compilation failed:\n--- STDOUT ---\n{}\n--- STDERR ---\n{}\n--- SOURCE ---\n{}\n",
            stdout,
            stderr,
            sil_source
        );
    }

    // Read JSON output
    let json_bytes =
        std::fs::read(&out_path).context("silverc succeeded but no output JSON was written")?;
    let abi_json: serde_json::Value =
        serde_json::from_slice(&json_bytes).context("Failed to parse silverc output JSON")?;

    // Extract bytecode
    let bytecode: Vec<u8> = abi_json["script"]
        .as_array()
        .context("silverc output missing 'script' array")?
        .iter()
        .map(|v| v.as_u64().unwrap_or(0) as u8)
        .collect();

    // Build script_hex (pure bytecode hex)
    let script_hex: String = bytecode.iter().map(|b| format!("{:02x}", b)).collect();

    // Build payload_hex (0xaa20 prefix + bytecode)
    let mut payload = vec![0xaa, 0x20];
    payload.extend_from_slice(&bytecode);
    let payload_hex: String = payload.iter().map(|b| format!("{:02x}", b)).collect();

    let contract_name = abi_json["contract_name"]
        .as_str()
        .unwrap_or(&unit.covenant_name)
        .to_string();

    // Cleanup temp files
    let _ = std::fs::remove_file(&src_path);
    let _ = std::fs::remove_file(&args_path);
    let _ = std::fs::remove_file(&out_path);

    Ok(CompiledOutput {
        contract_name,
        bytecode,
        script_hex,
        abi_json,
        payload_hex,
    })
}

/// Convenience function: parse + compile in one call.
pub fn compile_dsl(source: &str) -> Result<CompiledOutput> {
    let unit = parse_dsl(source)?;
    compile(&unit)
}

// ── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    /// The integration tests below shell out to the external `silverc` binary, which
    /// is installed on the dev box and the server but NOT on the GitHub CI runner.
    /// Skip them gracefully (rather than panic) when it is unavailable, mirroring the
    /// merkle-fixture skip in oracle.rs. The server gated deploy still runs them for real.
    fn silverc_available() -> bool {
        let p = silverc_path();
        if p != "silverc" {
            return std::path::Path::new(p).exists();
        }
        std::process::Command::new("silverc")
            .arg("--version")
            .output()
            .is_ok()
    }

    /// The exact Dice SilverScript output from generateSilverScriptForConfig()
    /// with gameType='dice', feePercent=2, resolutionMode='oracle'.
    /// Includes the ;; header comments needed by parse_dsl().
    const DICE_DSL: &str = r#";; DiceRollCovenant
;; Game: Dice
;; Fee: 2% | Resolution: oracle
;; Generated by Covex Premium Builder

Covenant DiceRollCovenant {
  fee_basis_points: 200
  platform_share:   20
  creator_share:    9980
  min_lock:         1000000

  input player_a: PubKey
  input player_b: PubKey
  input treasury:  PubKey
  input platform:  PubKey

  state locked_amount: u64 = 0
  ;; Reusable covenant
  OpReuseCovenant

  ;; ── Resolution: Covex Oracle (standard)

  fn unlock(outcome: Outcome::Win | Loss) {
    let total = locked_amount;
    let fee = (total * fee_basis_points) / 10000;
    let pot = total - fee;

    require(VerifyPayout(treasury, platform, fee), "Platform fee failed");

      Outcome::Win => {
        require(VerifyPayout(treasury, player_a, pot), "Win payout failed");
      }
      Outcome::Loss => {
        require(VerifyPayout(treasury, platform, pot), "Loss payout failed");
      }
  }
}"#;

    #[test]
    fn test_parse_dice_dsl() {
        let unit = parse_dsl(DICE_DSL).expect("Failed to parse Dice DSL");
        assert_eq!(unit.covenant_name, "DiceRollCovenant");
        assert_eq!(unit.game_type, "dice");
        assert_eq!(unit.fee_basis_points, 200);
        assert_eq!(unit.platform_share, 20);
        assert_eq!(unit.creator_share, 9980);
        assert_eq!(unit.min_lock, 1000000);
        assert!(unit.reusable);
        assert!(!unit.allow_topups);
        assert_eq!(unit.resolution_mode, "oracle");
        assert_eq!(unit.inputs.len(), 4);
        assert_eq!(
            unit.inputs[0],
            ("player_a".to_string(), "PubKey".to_string())
        );
        assert_eq!(unit.outcomes.len(), 2);
        assert_eq!(unit.outcomes[0].name, "Win");
        assert_eq!(unit.outcomes[1].name, "Loss");
    }

    #[test]
    fn test_emit_dice_silverscript() {
        let unit = parse_dsl(DICE_DSL).expect("Failed to parse Dice DSL");
        let sil = emit_silverscript(&unit);
        assert!(sil.starts_with("pragma silverscript ^0.1.0;"));
        assert!(sil.contains("contract DiceRollCovenant"));
        assert!(sil.contains("entrypoint function unlock"));
        assert!(sil.contains("REAL ENFORCEMENT (Phase 2)"));
        assert!(sil.contains("PLAYER A WINS"));
        assert!(sil.contains("PLAYER B WINS"));
        // Must not contain DSL-only keywords
        assert!(!sil.contains("Covenant {"));
        assert!(!sil.contains(";; "));
        assert!(!sil.contains("state "));
        assert!(!sil.contains("Outcome::"));
        // Must contain integer outcome range + fee check
        assert!(sil.contains("require(outcome >= 0 && outcome <= 1)"));
    }

    /// Integration test: compile Dice DSL through silverc.
    /// Requires silverc to be installed.
    #[test]
    fn test_compile_dice_through_silverc() {
        if !silverc_available() {
            eprintln!("Skipping test_compile_dice_through_silverc: silverc not installed");
            return;
        }
        let unit = parse_dsl(DICE_DSL).expect("Failed to parse Dice DSL");
        let output = compile(&unit).expect("silverc compilation failed");
        assert!(!output.bytecode.is_empty(), "Bytecode must not be empty");
        assert!(
            output.payload_hex.starts_with("aa20"),
            "Payload must start with aa20 prefix"
        );
        assert!(
            output.bytecode.len() < 200,
            "Compiled bytecode should be compact (<200 bytes)"
        );
        println!("Dice bytecode: {} bytes", output.bytecode.len());
        println!("Script hex: {}", output.script_hex);
        println!(
            "Payload hex (first 60): {}...",
            &output.payload_hex[..60.min(output.payload_hex.len())]
        );
    }

    // ── Chess DSL ───────────────────────────────────────────────────────

    const CHESS_DSL: &str = r#";; ChessReusableCovenant
;; Game: Chess
;; Fee: 2% | Resolution: oracle
;; Generated by Covex Premium Builder

Covenant ChessReusableCovenant {
  fee_basis_points: 200
  platform_share:   20
  creator_share:    9980
  min_lock:         1000000

  input player_a: PubKey
  input player_b: PubKey
  input treasury:  PubKey
  input platform:  PubKey

  state locked_amount: u64 = 0
  ;; Reusable covenant
  OpReuseCovenant

  ;; ── Resolution: Covex Oracle (standard)

  fn unlock(outcome: Outcome::PlayerAWins | PlayerBWin | Draw) {
    let total = locked_amount;
    let fee = (total * fee_basis_points) / 10000;
    let pot = total - fee;

    require(VerifyPayout(treasury, platform, fee), "Platform fee failed");

      Outcome::PlayerAWins => {
        require(VerifyPayout(treasury, player_a, pot), "Payout to Player A failed");
      }
      Outcome::PlayerBWin => {
        require(VerifyPayout(treasury, player_b, pot), "Payout to Player B failed");
      }
      Outcome::Draw => {
        let half = pot / 2;
        require(VerifyPayout(treasury, player_a, half) && VerifyPayout(treasury, player_b, half), "Draw payout failed");
      }
  }
}"#;

    #[test]
    fn test_parse_chess_dsl() {
        let unit = parse_dsl(CHESS_DSL).expect("Failed to parse Chess DSL");
        assert_eq!(unit.covenant_name, "ChessReusableCovenant");
        assert_eq!(unit.game_type, "chess");
        assert_eq!(unit.fee_basis_points, 200);
        assert_eq!(unit.outcomes.len(), 3);
        assert_eq!(unit.outcomes[0].name, "PlayerAWins");
        assert_eq!(unit.outcomes[1].name, "PlayerBWin");
        assert_eq!(unit.outcomes[2].name, "Draw");
    }

    #[test]
    fn test_emit_chess_silverscript() {
        let unit = parse_dsl(CHESS_DSL).expect("Failed to parse Chess DSL");
        let sil = emit_silverscript(&unit);
        assert!(sil.starts_with("pragma silverscript ^0.1.0;"));
        assert!(sil.contains("contract ChessReusableCovenant"));
        assert!(sil.contains("require(outcome >= 0 && outcome <= 2)"));
        assert!(!sil.contains("Covenant {"));
        assert!(!sil.contains("state "));
    }

    // ── Poker DSL ───────────────────────────────────────────────────────

    const POKER_DSL: &str = r#";; PokerHoldemCovenant
;; Game: Poker
;; Fee: 3% | Resolution: oracle
;; Generated by Covex Premium Builder

Covenant PokerHoldemCovenant {
  fee_basis_points: 300
  platform_share:   30
  creator_share:    9970
  min_lock:         5000000

  input player_a: PubKey
  input player_b: PubKey
  input treasury:  PubKey
  input platform:  PubKey

  state locked_amount: u64 = 0
  OpReuseCovenant

  ;; ── Resolution: Covex Oracle (standard)

  fn unlock(outcome: Outcome::PlayerAWins | PlayerBWin | Fold) {
    let total = locked_amount;
    let fee = (total * fee_basis_points) / 10000;
    let pot = total - fee;

    require(VerifyPayout(treasury, platform, fee), "Platform fee failed");

      Outcome::PlayerAWins => {
        require(VerifyPayout(treasury, player_a, pot), "Payout to Player A failed");
      }
      Outcome::PlayerBWin => {
        require(VerifyPayout(treasury, player_b, pot), "Payout to Player B failed");
      }
      Outcome::Fold => {
        require(VerifyPayout(treasury, player_a, pot), "Fold payout failed");
      }
  }
}"#;

    #[test]
    fn test_parse_poker_dsl() {
        let unit = parse_dsl(POKER_DSL).expect("Failed to parse Poker DSL");
        assert_eq!(unit.covenant_name, "PokerHoldemCovenant");
        assert_eq!(unit.game_type, "poker");
        assert_eq!(unit.fee_basis_points, 300);
        assert_eq!(unit.outcomes.len(), 3);
    }

    #[test]
    fn test_emit_poker_silverscript() {
        let unit = parse_dsl(POKER_DSL).expect("Failed to parse Poker DSL");
        let sil = emit_silverscript(&unit);
        assert!(sil.contains("contract PokerHoldemCovenant"));
        assert!(sil.contains("require(outcome >= 0 && outcome <= 2)"));
        assert!(!sil.contains("Covenant {"));
        assert!(!sil.contains("state "));
    }

    // ── Blackjack DSL ───────────────────────────────────────────────────

    const BLACKJACK_DSL: &str = r#";; BlackjackCovenant
;; Game: Blackjack
;; Fee: 2% | Resolution: oracle
;; Generated by Covex Premium Builder

Covenant BlackjackCovenant {
  fee_basis_points: 200
  platform_share:   20
  creator_share:    9980
  min_lock:         1000000

  input player_a: PubKey
  input player_b: PubKey
  input treasury:  PubKey
  input platform:  PubKey

  state locked_amount: u64 = 0
  OpReuseCovenant

  ;; ── Resolution: Covex Oracle (standard)

  fn unlock(outcome: Outcome::PlayerWin | DealerWin | Push | Bust) {
    let total = locked_amount;
    let fee = (total * fee_basis_points) / 10000;
    let pot = total - fee;

    require(VerifyPayout(treasury, platform, fee), "Platform fee failed");

      Outcome::PlayerWin => {
        require(VerifyPayout(treasury, player_a, pot), "Player payout failed");
      }
      Outcome::DealerWin => {
        require(VerifyPayout(treasury, platform, pot), "House wins pot");
      }
      Outcome::Push => {
        let half = pot / 2;
        require(VerifyPayout(treasury, player_a, half) && VerifyPayout(treasury, player_b, half), "Push refund failed");
      }
      Outcome::Bust => {
        require(VerifyPayout(treasury, platform, pot), "Bust payout failed");
      }
  }
}"#;

    #[test]
    fn test_parse_blackjack_dsl() {
        let unit = parse_dsl(BLACKJACK_DSL).expect("Failed to parse Blackjack DSL");
        assert_eq!(unit.covenant_name, "BlackjackCovenant");
        assert_eq!(unit.game_type, "blackjack");
        assert_eq!(unit.fee_basis_points, 200);
        assert_eq!(unit.outcomes.len(), 4);
        assert_eq!(unit.outcomes[0].name, "PlayerWin");
        assert_eq!(unit.outcomes[1].name, "DealerWin");
        assert_eq!(unit.outcomes[2].name, "Push");
        assert_eq!(unit.outcomes[3].name, "Bust");
    }

    #[test]
    fn test_emit_blackjack_silverscript() {
        let unit = parse_dsl(BLACKJACK_DSL).expect("Failed to parse Blackjack DSL");
        let sil = emit_silverscript(&unit);
        assert!(sil.contains("contract BlackjackCovenant"));
        assert!(sil.contains("require(outcome >= 0 && outcome <= 3)"));
        assert!(!sil.contains("Covenant {"));
        assert!(!sil.contains("state "));
    }

    /// Integration test: compile Blackjack DSL through silverc.
    /// Requires silverc to be installed.
    #[test]
    fn test_compile_blackjack_through_silverc() {
        if !silverc_available() {
            eprintln!("Skipping test_compile_blackjack_through_silverc: silverc not installed");
            return;
        }
        let unit = parse_dsl(BLACKJACK_DSL).expect("Failed to parse Blackjack DSL");
        let output = compile(&unit).expect("silverc compilation failed");
        assert!(!output.bytecode.is_empty(), "Bytecode must not be empty");
        assert!(output.payload_hex.starts_with("aa20"));
        assert!(
            output.bytecode.len() < 200,
            "Compiled bytecode should be compact (<200 bytes)"
        );
        println!("Blackjack bytecode: {} bytes", output.bytecode.len());
        println!("Script hex: {}", output.script_hex);
        println!(
            "Payload hex (first 60): {}...",
            &output.payload_hex[..60.min(output.payload_hex.len())]
        );
    }
}
