// compiler.rs — Covex DSL → SilverScript → silverc compilation pipeline
//
// This module takes Covex DSL source text (as generated by the frontend's
// generateSilverScriptForConfig()) and produces compiled Kaspa Script bytecode
// via the official silverc compiler.
//
// Architecture:
//   Covex DSL text → parse_dsl() → CompileUnit → emit_silverscript() → .sil file → silverc → bytecode
//
// Game-specific translation logic lives in the emit_<game>() functions.
// The DSL parser is regex-based and tolerant of minor formatting variations.

use anyhow::{bail, Context, Result};
use regex::Regex;
use serde::{Deserialize, Serialize};
use std::process::Command;

// ── Data structures ────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompileUnit {
    pub game_type: String,
    pub covenant_name: String,
    pub fee_basis_points: u64,
    pub platform_share: u64,
    pub creator_share: u64,
    pub min_lock: u64,
    pub inputs: Vec<(String, String)>, // (name, type) — e.g. ("player_a", "PubKey")
    pub resolution_mode: String,       // "oracle" | "custom" | "zk"
    pub oracle_key: Option<String>,
    pub zk_verifier_key: Option<String>,
    pub reusable: bool,
    pub allow_topups: bool,
    pub outcomes: Vec<OutcomeBranch>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OutcomeBranch {
    pub name: String,
    pub payouts: Vec<PayoutTarget>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PayoutTarget {
    pub recipient: String, // "player_a", "player_b", "platform", "treasury"
    pub share: PayoutShare,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PayoutShare {
    All,                                           // Entire pot
    Fraction { numerator: u64, denominator: u64 }, // e.g. 1/2 for draw
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompiledOutput {
    pub contract_name: String,
    pub bytecode: Vec<u8>,           // Raw Kaspa Script bytecodes from silverc
    pub script_hex: String,          // Hex-encoded bytecode
    pub abi_json: serde_json::Value, // Full silverc output JSON
    pub payload_hex: String,         // 0xaa20-prefixed hex for tx.payload
}

// ── DSL Parser ─────────────────────────────────────────────────────────────

/// Parse Covex DSL source text into a structured CompileUnit.
pub fn parse_dsl(source: &str) -> Result<CompileUnit> {
    // Extract covenant name
    let name_re = Regex::new(r"Covenant\s+(\w+)\s*\{").unwrap();
    let covenant_name = name_re
        .captures(source)
        .and_then(|c| c.get(1).map(|m| m.as_str().to_string()))
        .unwrap_or_else(|| "Covenant".to_string());

    // Extract game type from header comment
    let game_re = Regex::new(r";;\s*Game:\s*(.+)").unwrap();
    let game_type = game_re
        .captures(source)
        .and_then(|c| c.get(1).map(|m| m.as_str().trim().to_lowercase()))
        .unwrap_or_else(|| "custom".to_string());

    // Extract numeric fields
    let num = |pat: &str| -> u64 {
        Regex::new(&format!(r"{}\s*:\s*(\d+)", regex::escape(pat)))
            .ok()
            .and_then(|re| re.captures(source))
            .and_then(|c| c.get(1))
            .and_then(|m| m.as_str().parse().ok())
            .unwrap_or(0)
    };

    let fee_basis_points = num("fee_basis_points");
    let platform_share = num("platform_share");
    let creator_share = num("creator_share");
    let min_lock = num("min_lock");

    // Extract inputs
    let input_re = Regex::new(r"input\s+(\w+)\s*:\s*(\w+)").unwrap();
    let inputs: Vec<(String, String)> = input_re
        .captures_iter(source)
        .map(|c| (c[1].to_string(), c[2].to_string()))
        .collect();

    // Extract resolution mode from comment
    let res_re = Regex::new(r";; ── Resolution:\s*(.+?)(?:\s|$)").unwrap();
    let resolution_mode = res_re
        .captures(source)
        .and_then(|c| c.get(1).map(|m| m.as_str().trim().to_lowercase()))
        .map(|s| {
            if s.contains("zk") {
                "zk".to_string()
            } else if s.contains("custom") {
                "custom".to_string()
            } else {
                "oracle".to_string()
            }
        })
        .unwrap_or_else(|| "oracle".to_string());

    // Extract oracle/zk keys
    let oracle_key = Regex::new(r";; Key:\s*(.+)")
        .ok()
        .and_then(|re| re.captures(source))
        .and_then(|c| c.get(1).map(|m| m.as_str().trim().to_string()))
        .filter(|s| !s.is_empty() && s != "...");

    let zk_key = Regex::new(r";; Verifier:\s*(.+)")
        .ok()
        .and_then(|re| re.captures(source))
        .and_then(|c| c.get(1).map(|m| m.as_str().trim().to_string()))
        .filter(|s| !s.is_empty() && s != "built-in");

    // Extract flags
    let reusable = source.contains("OpReuseCovenant");
    let allow_topups = source.contains("OpAddToPot");

    // Extract outcomes
    let outcomes = parse_outcomes(source, &game_type)?;

    Ok(CompileUnit {
        game_type,
        covenant_name,
        fee_basis_points,
        platform_share,
        creator_share,
        min_lock,
        inputs,
        resolution_mode,
        oracle_key,
        zk_verifier_key: zk_key,
        reusable,
        allow_topups,
        outcomes,
    })
}

/// Parse outcome branches from the DSL source.
fn parse_outcomes(source: &str, game_type: &str) -> Result<Vec<OutcomeBranch>> {
    let mut outcomes = Vec::new();

    let outcome_re = Regex::new(r"Outcome::(\w+)\s*=>\s*\{([^}]+)\}").unwrap();
    let payout_re = Regex::new(r"VerifyPayout\(\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*\)").unwrap();

    for cap in outcome_re.captures_iter(source) {
        let name = cap[1].to_string();
        let body = cap[2].to_string();

        let mut payouts = Vec::new();

        if body.contains("half = pot / 2") || body.contains("half = pot/2") {
            for pc in payout_re.captures_iter(&body) {
                let recipient = pc[2].to_string();
                let amount_var = pc[3].to_string();
                let share = if amount_var == "half" {
                    PayoutShare::Fraction {
                        numerator: 1,
                        denominator: 2,
                    }
                } else {
                    PayoutShare::All
                };
                if !payouts
                    .iter()
                    .any(|p: &PayoutTarget| p.recipient == recipient)
                {
                    payouts.push(PayoutTarget { recipient, share });
                }
            }
        } else {
            for pc in payout_re.captures_iter(&body) {
                let recipient = pc[2].to_string();
                payouts.push(PayoutTarget {
                    recipient,
                    share: PayoutShare::All,
                });
            }
        }

        if payouts.is_empty() {
            payouts = infer_payouts(game_type, &name);
        }

        outcomes.push(OutcomeBranch { name, payouts });
    }

    if outcomes.is_empty() {
        bail!(
            "No outcome branches found in DSL source for game type '{}'",
            game_type
        );
    }

    Ok(outcomes)
}

/// Infer payout targets for known game types when parsing fails.
fn infer_payouts(game_type: &str, outcome_name: &str) -> Vec<PayoutTarget> {
    match (game_type, outcome_name) {
        ("dice", "Win") => vec![PayoutTarget {
            recipient: "player_a".into(),
            share: PayoutShare::All,
        }],
        ("dice", "Loss") => vec![PayoutTarget {
            recipient: "platform".into(),
            share: PayoutShare::All,
        }],
        _ => vec![PayoutTarget {
            recipient: "player_a".into(),
            share: PayoutShare::All,
        }],
    }
}

// ── SilverScript Emitter ───────────────────────────────────────────────────

/// Emit valid SilverScript source code for a CompileUnit.
pub fn emit_silverscript(unit: &CompileUnit) -> String {
    match unit.game_type.as_str() {
        "dice" => emit_dice(unit),
        _ => emit_generic(unit),
    }
}

/// Emit SilverScript for Dice (Win/Loss, two outcomes).
/// NOTE: Uses only int params in constructor because silverc constructor args
/// currently only support int/bool/bytes (not pubkey). The signer handles
/// pubkey embedding at deploy time by baking addresses into the bytecode or
/// providing them as witness data.
fn emit_dice(unit: &CompileUnit) -> String {
    let mut out = String::new();
    out.push_str("pragma silverscript ^0.1.0;\n\n");

    // Contract with int-only constructor params (silverc limitation for --constructor-args)
    out.push_str(&format!(
        "contract {}(\n    int feeBasisPoints,\n    int minLock\n) {{\n",
        unit.covenant_name
    ));

    out.push_str("    entrypoint function unlock(int outcome) {\n");
    out.push_str("        require(outcome == 0 || outcome == 1);\n");
    out.push_str(&format!(
        "        require(feeBasisPoints == {});\n",
        unit.fee_basis_points
    ));
    out.push_str(&format!("        require(minLock == {});\n", unit.min_lock));
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

/// Emit generic SilverScript for unknown game types — minimal valid contract.
fn emit_generic(unit: &CompileUnit) -> String {
    format!(
        "pragma silverscript ^0.1.0;\n\n\
         contract {name}() {{\n\
             entrypoint function unlock() {{\n\
                 require(true);\n\
             }}\n\
         }}\n",
        name = unit.covenant_name
    )
}

// ── Compilation ────────────────────────────────────────────────────────────

/// Build a constructor args JSON for silverc from a CompileUnit.
fn build_constructor_args(unit: &CompileUnit) -> serde_json::Value {
    match unit.game_type.as_str() {
        "dice" => serde_json::json!([
            {"kind": "int", "data": unit.fee_basis_points},
            {"kind": "int", "data": unit.min_lock}
        ]),
        _ => serde_json::json!([]),
    }
}

/// Compile a CompileUnit through silverc.
pub fn compile(unit: &CompileUnit) -> Result<CompiledOutput> {
    let sil_source = emit_silverscript(unit);

    let tmp_dir = std::env::temp_dir();
    let src_path = tmp_dir.join(format!("covex_{}.sil", unit.covenant_name.to_lowercase()));
    std::fs::write(&src_path, &sil_source).context("Failed to write temporary .sil file")?;

    let args_path = tmp_dir.join(format!(
        "covex_{}_args.json",
        unit.covenant_name.to_lowercase()
    ));
    let args = build_constructor_args(unit);
    std::fs::write(&args_path, serde_json::to_string_pretty(&args)?)
        .context("Failed to write constructor args file")?;

    let out_path = tmp_dir.join(format!("covex_{}.json", unit.covenant_name.to_lowercase()));

    // Run silverc
    let mut cmd = Command::new("silverc");
    cmd.arg(&src_path).arg("-o").arg(&out_path);

    // Only pass --constructor-args if there are params
    if !args.as_array().map(|a| a.is_empty()).unwrap_or(true) {
        cmd.arg("--constructor-args").arg(&args_path);
    }

    let output = cmd
        .output()
        .context("Failed to execute silverc — is it installed? (cargo install silverscript)")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let stdout = String::from_utf8_lossy(&output.stdout);
        bail!(
            "silverc compilation failed:\n--- STDOUT ---\n{}\n--- STDERR ---\n{}\n--- SOURCE ---\n{}\n",
            stdout,
            stderr,
            sil_source
        );
    }

    // Read JSON output
    let json_bytes =
        std::fs::read(&out_path).context("silverc succeeded but no output JSON was written")?;
    let abi_json: serde_json::Value =
        serde_json::from_slice(&json_bytes).context("Failed to parse silverc output JSON")?;

    // Extract bytecode
    let bytecode: Vec<u8> = abi_json["script"]
        .as_array()
        .context("silverc output missing 'script' array")?
        .iter()
        .map(|v| v.as_u64().unwrap_or(0) as u8)
        .collect();

    // Build script_hex (pure bytecode hex)
    let script_hex: String = bytecode.iter().map(|b| format!("{:02x}", b)).collect();

    // Build payload_hex (0xaa20 prefix + bytecode)
    let mut payload = vec![0xaa, 0x20];
    payload.extend_from_slice(&bytecode);
    let payload_hex: String = payload.iter().map(|b| format!("{:02x}", b)).collect();

    let contract_name = abi_json["contract_name"]
        .as_str()
        .unwrap_or(&unit.covenant_name)
        .to_string();

    // Cleanup temp files
    let _ = std::fs::remove_file(&src_path);
    let _ = std::fs::remove_file(&args_path);
    let _ = std::fs::remove_file(&out_path);

    Ok(CompiledOutput {
        contract_name,
        bytecode,
        script_hex,
        abi_json,
        payload_hex,
    })
}

/// Convenience function: parse + compile in one call.
pub fn compile_dsl(source: &str) -> Result<CompiledOutput> {
    let unit = parse_dsl(source)?;
    compile(&unit)
}

// ── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    /// The exact Dice SilverScript output from generateSilverScriptForConfig()
    /// with gameType='dice', feePercent=2, resolutionMode='oracle'.
    /// Includes the ;; header comments needed by parse_dsl().
    const DICE_DSL: &str = r#";; DiceRollCovenant
;; Game: Dice
;; Fee: 2% | Resolution: oracle
;; Generated by Covex Premium Builder

Covenant DiceRollCovenant {
  fee_basis_points: 200
  platform_share:   20
  creator_share:    9980
  min_lock:         1000000

  input player_a: PubKey
  input player_b: PubKey
  input treasury:  PubKey
  input platform:  PubKey

  state locked_amount: u64 = 0
  ;; Reusable covenant
  OpReuseCovenant

  ;; ── Resolution: Covex Oracle (standard)

  fn unlock(outcome: Outcome::Win | Loss) {
    let total = locked_amount;
    let fee = (total * fee_basis_points) / 10000;
    let pot = total - fee;

    require(VerifyPayout(treasury, platform, fee), "Platform fee failed");

      Outcome::Win => {
        require(VerifyPayout(treasury, player_a, pot), "Win payout failed");
      }
      Outcome::Loss => {
        require(VerifyPayout(treasury, platform, pot), "Loss payout failed");
      }
  }
}"#;

    #[test]
    fn test_parse_dice_dsl() {
        let unit = parse_dsl(DICE_DSL).expect("Failed to parse Dice DSL");
        assert_eq!(unit.covenant_name, "DiceRollCovenant");
        assert_eq!(unit.game_type, "dice");
        assert_eq!(unit.fee_basis_points, 200);
        assert_eq!(unit.platform_share, 20);
        assert_eq!(unit.creator_share, 9980);
        assert_eq!(unit.min_lock, 1000000);
        assert!(unit.reusable);
        assert!(!unit.allow_topups);
        assert_eq!(unit.resolution_mode, "oracle");
        assert_eq!(unit.inputs.len(), 4);
        assert_eq!(
            unit.inputs[0],
            ("player_a".to_string(), "PubKey".to_string())
        );
        assert_eq!(unit.outcomes.len(), 2);
        assert_eq!(unit.outcomes[0].name, "Win");
        assert_eq!(unit.outcomes[1].name, "Loss");
    }

    #[test]
    fn test_emit_dice_silverscript() {
        let unit = parse_dsl(DICE_DSL).expect("Failed to parse Dice DSL");
        let sil = emit_silverscript(&unit);
        assert!(sil.starts_with("pragma silverscript ^0.1.0;"));
        assert!(sil.contains("contract DiceRollCovenant"));
        assert!(sil.contains("entrypoint function unlock"));
        // Must not contain DSL-only keywords
        assert!(!sil.contains("Covenant {")); // DSL keyword
        assert!(!sil.contains(";; ")); // DSL comment style
        assert!(!sil.contains("state ")); // DSL state block
        assert!(!sil.contains("Outcome::")); // DSL outcome syntax
                                             // Must contain integer game logic
        assert!(sil.contains("require(outcome == 0 || outcome == 1)"));
    }

    /// Integration test: compile Dice DSL through silverc.
    /// Requires silverc to be installed.
    #[test]
    fn test_compile_dice_through_silverc() {
        let unit = parse_dsl(DICE_DSL).expect("Failed to parse Dice DSL");
        let output = compile(&unit).expect("silverc compilation failed");
        assert!(!output.bytecode.is_empty(), "Bytecode must not be empty");
        assert!(
            output.payload_hex.starts_with("aa20"),
            "Payload must start with aa20 prefix"
        );
        assert!(
            output.bytecode.len() < 200,
            "Compiled bytecode should be compact (<200 bytes)"
        );
        println!("Dice bytecode: {} bytes", output.bytecode.len());
        println!("Script hex: {}", output.script_hex);
        println!(
            "Payload hex (first 60): {}...",
            &output.payload_hex[..60.min(output.payload_hex.len())]
        );
    }
}
