//! Kaspa wallet message-signature verification.
//!
//! Real extension wallets (kasware, etc.) sign a message with the rusty-kaspa
//! "personal message" scheme: hash = PersonalMessageSigningHash(message)
//! (a domain-separated blake2b-256), then a BIP340 schnorr signature over that
//! digest with the wallet's key. The public key is recoverable from the
//! address (schnorr P2PK addresses carry the 32-byte x-only key as payload).
//!
//! This lets the backend cryptographically verify that whoever is editing a
//! covenant's Studio/FIX page actually controls the covenant's address, instead
//! of the old string-compare fallback (which anyone could spoof, since creator
//! addresses are public).
//!
//! The scheme is validated against fixtures generated by @onekeyfe/kaspa-wasm
//! (the library kasware is built on) - see the tests below and
//! frontend/kaspa-msg-fixture.mjs.

use kaspa_addresses::Address;
use secp256k1::{schnorr::Signature, Message, Secp256k1, XOnlyPublicKey};

/// Verify that `signature_hex` is a valid Kaspa wallet signature of `message`
/// by the schnorr P2PK key encoded in `address`.
///
/// Returns Ok(true) on a valid signature, Ok(false) on a well-formed but
/// non-matching signature, and Err only when the address or signature is
/// malformed (or the address is not a schnorr P2PK address).
pub fn verify_message(address: &str, message: &str, signature_hex: &str) -> Result<bool, String> {
    let addr = Address::try_from(address).map_err(|e| format!("invalid address: {}", e))?;
    let payload = addr.payload.as_slice();
    if payload.len() != 32 {
        return Err(format!(
            "address is not a schnorr P2PK address (payload {} bytes, expected 32)",
            payload.len()
        ));
    }
    let xonly = XOnlyPublicKey::from_slice(payload).map_err(|e| format!("bad public key: {}", e))?;

    let mut hasher = kaspa_hashes::PersonalMessageSigningHash::new();
    hasher.write(message.as_bytes());
    let hash = hasher.finalize();
    let msg = Message::from_digest(hash.as_bytes());

    let sig_bytes =
        hex::decode(signature_hex.trim_start_matches("0x")).map_err(|e| format!("bad signature hex: {}", e))?;
    let sig = Signature::from_slice(&sig_bytes).map_err(|e| format!("bad signature: {}", e))?;

    Ok(Secp256k1::verification_only()
        .verify_schnorr(&sig, &msg, &xonly)
        .is_ok())
}

#[cfg(test)]
mod tests {
    use super::*;

    // Ground-truth fixtures generated by @onekeyfe/kaspa-wasm (the library
    // kasware is built on) via frontend/kaspa-msg-fixture.mjs. If verify_message
    // accepts these, the scheme matches real extension-wallet signatures.
    // (address, message, signature)
    const FIXTURES: &[(&str, &str, &str)] = &[
        (
            "kaspatest:qpkke2kzfzheda405lusfa2sy5aq70hn7k4zle5r322my9nfz35wyz3plwfst",
            "covex-config:b261d39f5d4766c6da1ffa5fe95d01ff77aea61c575a1d2a665d6bdc78e31132:11111111-2222-3333-4444-555555555555",
            "d942c2359adb0997c2f7dacc7454acc56a0c7633b704ecd3924a86cf512130e70c837bfed16050d98ce82bb1db2594a4994c321061617ff0a2b7004bcca9a88a",
        ),
        (
            "kaspatest:qpkke2kzfzheda405lusfa2sy5aq70hn7k4zle5r322my9nfz35wyz3plwfst",
            "hello kaspa",
            "4829dcd79c2047f1a70bfc0b8c04074b0f988062e51a03ad76727bc7a2ee7650bee64c5e2fca633673fdc76b407cfbcfcd274f21884dff975d9ef7176cedd34e",
        ),
        (
            "kaspatest:qprx6l72u437tjcf5rgcwza4sq6ysprp0pu6zj2feu3zshcm4cljwrzqrunpu",
            "covex-config:b261d39f5d4766c6da1ffa5fe95d01ff77aea61c575a1d2a665d6bdc78e31132:11111111-2222-3333-4444-555555555555",
            "ac952d11887478cc4787b7b4b1c395f64b180615cc7d8f3713c0928a591cca0cc357806a211fa029367625fcd0607a650e4587d3ccb2e62b294a82a89f809239",
        ),
    ];

    #[test]
    fn verifies_kaspa_wasm_fixtures() {
        for (addr, msg, sig) in FIXTURES {
            assert!(
                verify_message(addr, msg, sig).expect("well-formed"),
                "should verify real kaspa-wasm signature for: {}",
                msg
            );
        }
    }

    #[test]
    fn rejects_tampered_message() {
        let (addr, _msg, sig) = FIXTURES[0];
        assert!(!verify_message(addr, "covex-config:tampered:nonce", sig).expect("well-formed"));
    }

    #[test]
    fn rejects_wrong_signer() {
        // signature from key #1, but verified against key #2's address
        let other_addr = FIXTURES[2].0;
        let (_a, msg, sig) = FIXTURES[0];
        assert!(!verify_message(other_addr, msg, sig).expect("well-formed"));
    }
}
