// oracle_verifier.rs
//
// Pluggable verifier registry and helpers for the Covex Oracle.
//
// Goal (per ZK_ORACLE_FULL_STACK_VISION_AND_ROADMAP.md Phase 0 and §6):
//   - Make oracle fully pluggable: config-driven / map dispatch instead of giant
//     hardcoded match on circuit_type in oracle.rs.
//   - Support expanded stack: Groth16 (via existing snarkjs/node scripts),
//     RISC0 stub (invoke risc0 binary if available, else accept for dev/attested),
//     WASM exec stub (similar), plus AttestedOnly for the long tail.
//   - Dynamic registry map (HashMap) so adding new circuit_types (ownership, VRF,
//     DeFi, compute, data oracles, primitives per vision §4) is just an insert.
//   - Deduped common run logic (no more copy-paste per circuit).
//   - Stubs for 100+ circuit types from current ZK_CIRCUIT_TYPES + vision inventory.
//
// Usage coordination (do NOT edit this file for integration; edit oracle.rs + main.rs):
//   In backend/src/main.rs, add near other mods:
//     mod oracle_verifier;
//   In backend/src/oracle.rs (suggested refactor notes; main work remains there):
//     Add at top:
//       use crate::oracle_verifier::{
//           verify_proof_for_circuit, determine_outcome_for_circuit,
//           proof_has_groth16_body, VerifierSpec,
//       };
//     Replace the giant `let _valid = match input.circuit_type.as_str() { ... }`
//     (and duplicated error returns) with:
//       let verified = verify_proof_for_circuit(
//           &input.circuit_type,
//           input.proof.clone(),
//           input.public_inputs.clone(),
//           input.requested_outcome,
//       ).await;
//       if !verified {
//           return Json(OracleVerifyOutput { success: false, ... error: Some("ZK ...".into()), ... });
//       }
//       let _valid = true;
//     Similarly, replace the big outcome derivation chain with:
//       let outcome = determine_outcome_for_circuit(
//           &input.circuit_type, &input.proof, &input.public_inputs, input.requested_outcome
//       );
//     Keep multi-oracle sig verification + final signing in oracle.rs (they need
//     DB Extension / special side effects).
//     The old per-circuit verify_*_path() and verify_*_proof() fns can be removed
//     or deprecated to call through here once refactored.
//   This keeps oracle.rs as the HTTP + signing orchestrator while verifiers are
//   pluggable here. Future: trait object dispatch, external plugin loading, or
//   config file for circuits -> verifier kind + script.
//
// Reality labels (honest): full-zk entries use real artifacts when present;
// everything else (vast majority per vision) starts as oracle-attested or hybrid
// and can graduate. Registry can be extended with reality metadata later.
//
// No new Cargo deps. Uses std + existing (uuid via crate name, tracing, etc.).
// File created in /tmp/covex27/backend/src/oracle_verifier.rs

use std::collections::HashMap;
use std::path::PathBuf;
use std::process::Command;
use std::sync::OnceLock;

use serde_json::Value;

/// Supported verifier kinds in the pluggable registry.
/// Easy to extend for SP1, Halo2, etc. in future phases.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) enum VerifierSpec {
    /// Real Groth16 via snarkjs; always run the verifier script (merkle, range, timelock, hash).
    StrictGroth16 {
        script: &'static str,
        prefix: &'static str,
    },
    /// Groth16 when proof body present (pi_a etc), else treat as oracle-attested success.
    /// Used for the game hybrids tictactoe_v1, connect4_v1.
    HybridGroth16 {
        script: &'static str,
        prefix: &'static str,
    },
    /// RISC0 receipt verification. If risc0 binary (or cargo risc0) found, attempt invoke
    /// (stubbed; real would feed receipt json); otherwise accept (dev + attested fallback).
    Risc0Stub { guest: &'static str },
    /// WASM execution / predicate proof. Stub: runtime if present (wasmtime/node), else accept.
    WasmStub { module_hint: &'static str },
    /// Pure oracle attestation / hybrid property proof (off-chain engine + requested_outcome).
    /// This is the path for the overwhelming majority of the expanded stack.
    Attested,
    /// HONEST "not claimable yet": the circom source, the verify script and the served vkey
    /// exist, but there is NO served `_final.zkey`, so an in-browser prover can never generate a
    /// Groth16 proof for it. Such a circuit must NOT be presented as Groth16-claimable (that
    /// would advertise a ZK claim that always fails closed) and must NOT be attested-with-a-
    /// caller-chosen-outcome (that would sign an unverified outcome). circuit_requires_crypto_proof
    /// returns false for this kind, and verify_proof_for_circuit fails closed with a clear reason.
    /// Promote to Strict/Hybrid only once a trusted setup ships the served proving key.
    SourceOnlyNoZkey { reason: &'static str },
}

/// Returns the static registry map: circuit_type -> verifier spec.
/// Populated once. Adding support for new vision circuits (e.g. utxo_*, vrf_*, defi_*,
/// compute_*, price_*, more primitives) is a one-line insert here. No match arms to touch.
pub(crate) fn get_registry() -> &'static HashMap<&'static str, VerifierSpec> {
    static REG: OnceLock<HashMap<&'static str, VerifierSpec>> = OnceLock::new();
    REG.get_or_init(build_registry)
}

fn build_registry() -> HashMap<&'static str, VerifierSpec> {
    let mut m: HashMap<&'static str, VerifierSpec> = HashMap::new();

    // === Real full-zk Groth16 (strict: always invoke snarkjs) ===
    // These have (or will have) real artifacts + vkeys in ../zk/
    m.insert(
        "merkle_membership",
        VerifierSpec::StrictGroth16 {
            script: "verify.js",
            prefix: "covex_merkle",
        },
    );
    m.insert(
        "merkle_dao",
        VerifierSpec::StrictGroth16 {
            script: "verify.js",
            prefix: "covex_merkle",
        },
    );
    m.insert(
        "merkle_airdrop",
        VerifierSpec::StrictGroth16 {
            script: "verify.js",
            prefix: "covex_merkle",
        },
    );
    m.insert(
        "range_proof",
        VerifierSpec::StrictGroth16 {
            script: "verify_range.js",
            prefix: "covex_range",
        },
    );
    m.insert(
        "range_collateral",
        VerifierSpec::StrictGroth16 {
            script: "verify_range.js",
            prefix: "covex_range",
        },
    );
    m.insert(
        "timelock_absolute",
        VerifierSpec::StrictGroth16 {
            script: "verify_timelock.js",
            prefix: "covex_tl",
        },
    );
    m.insert(
        "timelock_abs",
        VerifierSpec::StrictGroth16 {
            script: "verify_timelock.js",
            prefix: "covex_tl",
        },
    );
    m.insert(
        "hash_preimage",
        VerifierSpec::StrictGroth16 {
            script: "verify_hash_preimage.js",
            prefix: "covex_hp",
        },
    );
    m.insert(
        "age_verification",
        VerifierSpec::StrictGroth16 {
            script: "verify_age_verification.js",
            prefix: "covex_age",
        },
    );
    m.insert(
        "escrow_2party",
        VerifierSpec::StrictGroth16 {
            script: "verify_escrow_2party.js",
            prefix: "covex_escrow",
        },
    );
    // utxo_ownership is the frontend catalog alias for basic_utxo_ownership (same served
    // artifacts + verify script). basic_utxo_ownership, nullifier_set and vrf_dice_roll are
    // pinned StrictGroth16 in the dedicated block further down; this alias is registered here so
    // the catalog id resolves to the same fail-closed verifier. These ids are also REMOVED from
    // the crypto_attested / ownership_attested arrays below so the later loops cannot re-attest.
    m.insert(
        "utxo_ownership",
        VerifierSpec::StrictGroth16 {
            script: "verify_basic_utxo_ownership.js",
            prefix: "covex_utxo",
        },
    );

    // === Hybrids: Groth16 when supplied, else oracle-attested (current behavior) ===
    m.insert(
        "tictactoe_v1",
        VerifierSpec::HybridGroth16 {
            script: "verify_tictactoe.js",
            prefix: "covex_tt",
        },
    );
    m.insert(
        "connect4_v1",
        VerifierSpec::HybridGroth16 {
            script: "verify_connect4.js",
            prefix: "covex_c4",
        },
    );
    // privacy_mixer_v1 is intentionally NOT registered. The first-party privacy-mixer co-sign
    // path was removed for the legal / sanctions posture documented in main.rs, so the circuit
    // has no verifier and falls through to the fail-closed unknown-circuit branch in
    // verify_proof_for_circuit. scripts/check-no-privacy-mixer.sh guards against re-adding it.

    // === RISC0 / verifiable compute stubs (per vision §4.6, Phase 0 wire skeleton) ===
    m.insert("verifiable", VerifierSpec::Risc0Stub { guest: "generic" });
    m.insert(
        "risc0_generic",
        VerifierSpec::Risc0Stub { guest: "generic" },
    );
    m.insert("ml_inference", VerifierSpec::Risc0Stub { guest: "ml_stub" });
    m.insert(
        "poker_solver",
        VerifierSpec::Risc0Stub {
            guest: "poker_nash",
        },
    );
    // (chess risc0 removed)
    // Phase 3: new RISC0 guests added to risc0_guests/ (poker_solver.rs, financial_formula.rs)
    // Registered explicitly so "risc0_poker_solver", "verifiable_poker" dispatch to Risc0Stub path.
    m.insert(
        "risc0_poker_solver",
        VerifierSpec::Risc0Stub {
            guest: "poker_solver",
        },
    );
    m.insert(
        "verifiable_poker",
        VerifierSpec::Risc0Stub {
            guest: "poker_solver",
        },
    );
    m.insert(
        "risc0_financial_formula",
        VerifierSpec::Risc0Stub {
            guest: "financial_formula",
        },
    );
    // Phase 4 prep from sub-agent (chess_endgame removed)
    m.insert(
        "risc0_defi_liquidation",
        VerifierSpec::Risc0Stub {
            guest: "defi_liquidation",
        },
    );
    m.insert(
        "risc0_connect4_eval",
        VerifierSpec::Risc0Stub {
            guest: "connect4_eval",
        },
    );
    // Decentralized oracle skeleton (Phase 2: multi-provider, liveness stub)
    m.insert("decentralized_oracle", VerifierSpec::Attested);
    m.insert("multi_oracle_v2", VerifierSpec::Attested);
    // Phase 3 explicit: decentralized_liveness (for /liveness + POST) and onchain_sig_verify
    // (ties to onchain_sig_verify.circom stub) registered so they don't hit the None fallthrough.
    m.insert("decentralized_liveness", VerifierSpec::Attested);
    m.insert("onchain_sig_verify", VerifierSpec::Attested);
    m.insert("onchain_sig_verify_stub", VerifierSpec::Attested); // alias already in lists

    // === WASM exec / predicate stubs (vision §4.6, WASM for portability + custom logic) ===
    m.insert(
        "wasm_execution",
        VerifierSpec::WasmStub {
            module_hint: "generic",
        },
    );
    m.insert(
        "wasm_predicate",
        VerifierSpec::WasmStub {
            module_hint: "predicate",
        },
    );

    // === Attested / hybrid for everything else (expanded from frontend ZK_CIRCUIT_TYPES + vision) ===
    // Games (non full-zk)
    let game_attested = [
        "chess_v1",
        "chess_blitz",
        "chess_bullet",
        "poker_v1",
        "poker_6max",
        "poker_tourney",
        "blackjack_v1",
        "blackjack_multi",
        "rps_v1",
        "go_9x9",
        "go_13x13",
        "go_19x19",
        "backgammon_v1",
        "checkers_v1",
        "reversi_v1",
        "battleship_v1",
        "scrabble_v1",
        "dominoes_v1",
        "rummikub_v1",
        "mancala_v1",
        "risk_v1",
        "catan_v1",
        "monopoly_v1",
        "yahtzee_v1",
        "gin_rummy_v1",
        "hearts_v1",
        "spades_v1",
        "bridge_v1",
        "euchre_v1",
        "cribbage_v1",
        "mahjong_v1",
    ];
    for &id in &game_attested {
        m.insert(id, VerifierSpec::Attested);
    }

    // Crypto primitives (current + vision 4.1 expansions)
    let crypto_attested = [
        "schnorr_knowledge",
        "pedersen_commitment",
        "vrf_random",
        "vrf_shuffle",
        "bls_signature",
        "vrf_card_deal",
        "dao_multisig",
        // NOTE: nullifier_set + vrf_dice_roll are registered above as StrictGroth16 (full-zk), not here.
        // vision expansions
        "poseidon_commit",
        "sha256_preimage",
        "blake3_commit",
        // NOTE: merkle_multi_membership is now registered below as StrictGroth16 (real circuit +
        // served _final.zkey + vkey, node-verified accept + tamper-reject + false-predicate
        // valid==0), so it is REMOVED from this attested list to avoid the last-insert-wins
        // overwrite that would silently downgrade it to attested (caller-chosen outcome).
        "set_accumulator",
        "ecdsa_knowledge",
        "ring_signature",
        "adaptor_sig",
        "commit_reveal",
        "distributed_randomness",
        "timestamp_bound",
        "recursive_proof_verify",
        "pedersen",
        "mimc7",
        "poseidon",
        "blake2_commit",
        "sha256_commit",
    ];
    for &id in &crypto_attested {
        m.insert(id, VerifierSpec::Attested);
    }

    // Ownership / Script / Timelock / Kaspa-native (vision 4.2 highest priority)
    let ownership_attested = [
        "script_hash_match",
        "timelock_relative",
        "multisig_threshold",
        // NOTE: utxo_ownership + basic_utxo_ownership are registered above as StrictGroth16 (full-zk), not here.
        "state_transition",
        "vesting_schedule",
        "replay_protection",
        "utxo_spend_auth",
        "covenant_state_hash",
        "script_constraint_proof",
        // vision expansions (more ownership, script, state, cross)
        "relative_timelock",
        "selected_parent_proof",
        "utxo_set_proof",
        "covenant_state_commit",
        "fee_pot_math",
        "metadata_constraint",
        "silver_script_fragment",
        "oracle_pubkey_binding",
        "script_opcode_satisfy",
        "onchain_sig_verify_stub",
        "vesting_linear",
        "vesting_cliff",
        "multi_sig_threshold",
        "n_of_m_spend",
        "block_header_proof",
        "dag_inclusion",
    ];
    for &id in &ownership_attested {
        m.insert(id, VerifierSpec::Attested);
    }

    // DeFi / Economic (vision 4.4)
    let defi_attested = [
        "collateral_loan",
        "yield_accrual",
        "token_gated",
        "pot_distribution",
        "escrow_2party",
        "escrow_multiparty",
        "auction_dutch",
        "auction_english",
        "lending_pool",
        "prediction_market",
        "liquidation_threshold",
        "yield_compounding",
        // vision expansions
        "insurance_parametric",
        "fractional_ownership",
        "options_derivative",
        "dao_treasury_mgmt",
        "yield_farming_claim",
        "cross_asset_swap",
        "amm_invariant_proof",
        "black_scholes",
        "bond_yield",
        "dcf_valuation",
        "portfolio_var",
        "var_risk",
        "option_greeks",
        "lending_health",
        "liquidation_auction",
        "escrow_milestone",
        "prediction_tally",
    ];
    for &id in &defi_attested {
        m.insert(id, VerifierSpec::Attested);
    }

    // Verifiable Compute + Custom (vision 4.6; RISC0/WASM for heavy ones)
    let compute_attested = [
        "financial_formula",
        "sorting_proof",
        "graph_reachability",
        "zk_email",
        "basic_state_machine",
        // vision expansions (concrete programs + backends)
        "monte_carlo_sim",
        "linear_optimizer",
        "regex_string_match",
        "supply_chain_graph",
        "formal_verif_proof",
        "custom_compute",
        "simulation_engine",
        "optimization_lp",
        "string_regex",
        "graph_shortest",
        "ml_credit",
        "fraud_detect",
        "image_classify_stub",
        "custom_game_logic",
        "fsm_compiler",
        "python_subset_guest",
    ];
    for &id in &compute_attested {
        m.insert(id, VerifierSpec::Attested);
    }

    // Gating / Access / Identity (vision 4.8)
    let gating_attested = [
        "nft_gating",
        "reputation_threshold",
        "age_verification",
        "kyc_alternative",
        "private_group_membership",
        "anti_sybil_proof",
        "credential_proof",
        // vision
        "nft_collection_gate",
        "soulbound_gate",
        "rep_update_nullifier",
        "kyc_range",
        "location_bound",
        "income_bracket",
        "education_cred",
    ];
    for &id in &gating_attested {
        m.insert(id, VerifierSpec::Attested);
    }

    // Oracle / Data feeds / Real-world (vision 4.7) - treated as circuit_types for uniformity
    let data_oracle_attested = [
        "price_kas",
        "price_btc",
        "price_eth",
        "price_stable",
        "sports_nba",
        "sports_soccer",
        "weather_trigger",
        "election_result",
        "shipping_event",
        "drand_beacon",
        "web2_api_attest",
        "ai_model_output",
        "cross_chain_light_client",
        // vision specifics
        "price_gold",
        "price_oil",
        "price_spx",
        "nba_player_prop",
        "flight_delay",
        "hurricane_event",
        "governance_vote",
        "randomness_beacon",
    ];
    for &id in &data_oracle_attested {
        m.insert(id, VerifierSpec::Attested);
    }

    // Privacy expansions (vision 4.5, beyond the one full-zk mixer)
    let privacy_attested = [
        "private_transfer",
        "shielded_utxo",
        "private_vote",
        "private_airdrop",
        "private_reputation",
        "mixnet_metadata",
        "confidential_collateral",
    ];
    for &id in &privacy_attested {
        m.insert(id, VerifierSpec::Attested);
    }

    // Meta / self-referential / advanced (vision 4.9-4.10)
    let meta_attested = [
        "oracle_self_proof",
        "ceremony_contrib",
        "benchmark_attest",
        "circuit_registry_member",
        "artifact_hash_integrity",
        "liveness_heartbeat",
        "staking_commit",
        "recursive_aggregate",
        "folding_incremental",
    ];
    for &id in &meta_attested {
        m.insert(id, VerifierSpec::Attested);
    }

    // Always-supported escape hatches
    m.insert("custom", VerifierSpec::Attested);
    m.insert(
        "verifiable_compute",
        VerifierSpec::Risc0Stub { guest: "generic" },
    ); // alias

    // === High-value circuit stubs from Covex vision inventory (12-15 added) ===
    // oracle-attested or hybrid start; point to new minimal verify_*.js + .circom
    // (inserted late so Hybrid overrides any prior Attested from vision lists)
    m.insert(
        "poker_vrf_deal",
        VerifierSpec::HybridGroth16 {
            script: "verify_poker_vrf_deal.js",
            prefix: "covex_pvd",
        },
    );
    m.insert(
        "auction_clearing",
        VerifierSpec::HybridGroth16 {
            script: "verify_auction_clearing.js",
            prefix: "covex_auc",
        },
    );
    m.insert(
        "private_transfer_nullifier",
        VerifierSpec::HybridGroth16 {
            script: "verify_private_transfer_nullifier.js",
            prefix: "covex_ptn",
        },
    );
    m.insert(
        "election_feed",
        VerifierSpec::HybridGroth16 {
            script: "verify_election_feed.js",
            prefix: "covex_elec",
        },
    );
    // SECURITY (C1): ml_inference_stub has NO real circom circuit + committed vkey - its
    // verify script was a rubber-stamp delegator to verify_attested.js. Registering it as
    // Attested means circuit_requires_crypto_proof()==false, so the oracle handler refuses
    // to sign its caller-supplied outcome (no crypto proof can warrant a signature).
    m.insert("ml_inference_stub", VerifierSpec::Attested);
    // SECURITY (C1): weather_feed has NO real circom circuit - verify_weather_feed.js just
    // delegates to the neutered verify_attested.js. Registered Hybrid it could never validate a
    // legit proof AND would become a forgery path the instant that stub were un-neutered. Attested
    // makes circuit_requires_crypto_proof()==false, so the oracle refuses to sign its outcome.
    m.insert("weather_feed", VerifierSpec::Attested);
    // SECURITY (C1): sorting_proof has NO real circom circuit + committed vkey (rubber-stamp
    // delegator script). Attested so the oracle refuses to sign its outcome.
    m.insert("sorting_proof", VerifierSpec::Attested);
    // (chess_ai_move removed with chess zk circuit)
    // SECURITY (C1): poker_equity has NO real circuit (rubber-stamp delegator). Attested.
    m.insert("poker_equity", VerifierSpec::Attested);
    // HONESTY (registration): collateral_ltv / loan_health / financial_formula have a circom
    // source, a fail-closed verify script and a served vkey, but ship NO served _final.zkey on
    // prod, so an in-browser prover can never produce a Groth16 proof and the claim would ALWAYS
    // fail closed. Registered Hybrid they were advertised as Groth16-claimable yet were
    // unprovable (dishonest). Downgraded to SourceOnlyNoZkey so they are NOT presented as
    // claimable; promote back to Hybrid/Strict only once a trusted setup ships the served zkey.
    // (Their verify scripts already index the validity public signal correctly, so no soundness
    // change here, only an honest "not claimable yet" registration.)
    m.insert(
        "collateral_ltv",
        VerifierSpec::SourceOnlyNoZkey {
            reason: "no served proving key (collateral_ltv_final.zkey); circuit source + vkey exist but no proof can be generated yet",
        },
    );
    m.insert(
        "loan_health",
        VerifierSpec::SourceOnlyNoZkey {
            reason: "no served proving key (loan_health_final.zkey); circuit source + vkey exist but no proof can be generated yet",
        },
    );
    // multi_sig_gating + anon_credential: origin/master now ships zk/multi_sig_gating.circom and
    // zk/anon_credential.circom plus served wasm + vkey (the old "NO real circuit / rubber-stamp
    // delegator" note is stale). There is still NO served _final.zkey for either, so they remain
    // NOT-yet-claimable. They were registered Attested (oracle refuses to sign their outcome, so
    // never a forgery path); we keep them Attested rather than promoting to Hybrid, because a
    // Hybrid with no zkey would falsely advertise them as Groth16-claimable. Never present an
    // Attested circuit as ZK-verified.
    m.insert("multi_sig_gating", VerifierSpec::Attested);
    m.insert("anon_credential", VerifierSpec::Attested);
    m.insert(
        "financial_formula",
        VerifierSpec::SourceOnlyNoZkey {
            reason: "no served proving key (financial_formula_final.zkey); circuit source + vkey exist but no proof can be generated yet",
        },
    );
    // SECURITY (C1): verifiable_poker_solver has NO real circuit (rubber-stamp delegator). Attested.
    m.insert("verifiable_poker_solver", VerifierSpec::Attested);
    // Latest sub-agent Phase 0/1 circuits (relative timelock, VRF family, script constraints, pot split, turn timer)
    // Promoted Hybrid -> Strict after a live trusted setup produced matched keys and a
    // real proof verified end-to-end (tamper-rejected). Strict = always run snarkjs and
    // fail closed; a bodyless request can no longer be rubber-stamped to requested_outcome.
    m.insert(
        "relative_timelock",
        VerifierSpec::StrictGroth16 {
            script: "verify_relative_timelock.js",
            prefix: "covex_rtl",
        },
    );
    m.insert(
        "vrf_dice_roll",
        VerifierSpec::StrictGroth16 {
            script: "verify_vrf_dice_roll.js",
            prefix: "covex_vrf",
        },
    );
    m.insert(
        "vrf_random",
        VerifierSpec::StrictGroth16 {
            script: "verify_vrf_random.js",
            prefix: "covex_vrf",
        },
    );
    m.insert(
        "script_constraint",
        VerifierSpec::StrictGroth16 {
            script: "verify_script_constraint.js",
            prefix: "covex_script",
        },
    );
    m.insert(
        "pot_split_math",
        VerifierSpec::StrictGroth16 {
            script: "verify_pot_split_math.js",
            prefix: "covex_pot",
        },
    );
    m.insert(
        "turn_timer",
        VerifierSpec::StrictGroth16 {
            script: "verify_turn_timer.js",
            prefix: "covex_timer",
        },
    );
    m.insert(
        "basic_utxo_ownership",
        VerifierSpec::StrictGroth16 {
            script: "verify_basic_utxo_ownership.js",
            prefix: "covex_utxo",
        },
    );
    m.insert(
        "nullifier_set",
        VerifierSpec::StrictGroth16 {
            script: "verify_nullifier_set.js",
            prefix: "covex_null",
        },
    );
    // === New privacy / identity / solvency circuits (StrictGroth16, dev pot10/pot12 ceremony) ===
    // Each verified end-to-end on the server BEFORE registration: a genuine proof verifies true,
    // a tampered proof/public-signal verifies false, and a proof bound to covenant A is rejected
    // for covenant B (replay). Negative predicate cases produce valid==0 (or an unsatisfiable
    // witness), so these are real statements, not `valid <== 1` stubs. Verify scripts are STRICT
    // fail-closed (real snarkjs.groth16.verify vs the served vkey, {valid:false} on any failure,
    // NO attested fallback). Keys are a single-contributor Covex dev ceremony, NOT a production MPC.
    m.insert(
        "commitment_open",
        VerifierSpec::StrictGroth16 {
            script: "verify_commitment_open.js",
            prefix: "covex_copen",
        },
    );
    m.insert(
        "balance_threshold",
        VerifierSpec::StrictGroth16 {
            script: "verify_balance_threshold.js",
            prefix: "covex_bal",
        },
    );
    m.insert(
        "solvency_sum",
        VerifierSpec::StrictGroth16 {
            script: "verify_solvency_sum.js",
            prefix: "covex_solv",
        },
    );
    m.insert(
        "set_non_membership",
        VerifierSpec::StrictGroth16 {
            script: "verify_set_non_membership.js",
            prefix: "covex_snm",
        },
    );
    m.insert(
        "anon_membership_nullifier",
        VerifierSpec::StrictGroth16 {
            script: "verify_anon_membership_nullifier.js",
            prefix: "covex_anm",
        },
    );
    // === New self-contained primitives (zkwave 2026-06-28) ===
    // Each verified end-to-end with the SERVED wasm + _final.zkey + vkey BEFORE registration:
    // a real proof verifies true, a tampered proof verifies false, and a false predicate
    // (out-of-band value for merkle_range_membership, mismatched value for
    // equality_of_commitments) produces a VERIFYING proof whose computed valid==0 (so a
    // non-satisfying claim fails the gate). `valid` is a CONSTRAINED OUTPUT, not a `valid<==1`
    // stub. Verify scripts are STRICT fail-closed (real snarkjs.groth16.verify vs the served
    // vkey, {valid:false} on any failure, NO attested fallback). Keys are a single-contributor
    // Covex dev ceremony (pot10 / pot12), NOT a production MPC.
    m.insert(
        "merkle_range_membership",
        VerifierSpec::StrictGroth16 {
            script: "verify_merkle_range_membership.js",
            prefix: "covex_mrm",
        },
    );
    m.insert(
        "equality_of_commitments",
        VerifierSpec::StrictGroth16 {
            script: "verify_equality_of_commitments.js",
            prefix: "covex_eoc",
        },
    );
    // === New self-contained primitives (circomwave 2026-06-28) ===
    // Each verified end-to-end with the SERVED wasm + _final.zkey + vkey BEFORE registration:
    // a real proof verifies true, a tampered public-signal / pi_a verifies false, and a false
    // predicate (a leaf outside the set, a spent nullifier, mismatched shares, value != expected,
    // an out-of-order sorted value) produces a VERIFYING proof whose computed valid==0 (so a
    // non-satisfying claim fails the gate). `valid` is a CONSTRAINED OUTPUT (a product of
    // comparator/equality outputs), not a `valid<==1` stub. Verify scripts are STRICT fail-closed
    // (real snarkjs.groth16.verify vs the served vkey, {valid:false} on any failure, NO attested
    // fallback). Keys are a single-contributor Covex dev ceremony (pot10 / pot12), NOT a production
    // MPC; verified OFF-CHAIN by the disclosed oracle, never on-chain. merkle_multi_membership was
    // promoted here from the attested crypto-primitive stub list above.
    m.insert(
        "merkle_multi_membership",
        VerifierSpec::StrictGroth16 {
            script: "verify_merkle_multi_membership.js",
            prefix: "covex_mmm",
        },
    );
    m.insert(
        "nullifier_uniqueness",
        VerifierSpec::StrictGroth16 {
            script: "verify_nullifier_uniqueness.js",
            prefix: "covex_nuq",
        },
    );
    m.insert(
        "threshold_sig_knowledge",
        VerifierSpec::StrictGroth16 {
            script: "verify_threshold_sig_knowledge.js",
            prefix: "covex_tsk",
        },
    );
    m.insert(
        "pedersen_open_equals",
        VerifierSpec::StrictGroth16 {
            script: "verify_pedersen_open_equals.js",
            prefix: "covex_poe",
        },
    );
    m.insert(
        "sorted_merkle_range",
        VerifierSpec::StrictGroth16 {
            script: "verify_sorted_merkle_range.js",
            prefix: "covex_smr",
        },
    );
    // Re-assert as StrictGroth16 AFTER the attested loops above. age_verification and
    // escrow_2party were inserted Strict early (lines ~128/131) but the later
    // gating_attested / defi_attested loops overwrote them with Attested (HashMap: last
    // insert wins), which silently downgraded them to "sign requested_outcome" and made
    // them soft-pass an empty proof. Their verify scripts now fail closed on a bodyless
    // proof, so re-pinning them Strict here makes them genuinely require a real proof.
    m.insert(
        "age_verification",
        VerifierSpec::StrictGroth16 {
            script: "verify_age_verification.js",
            prefix: "covex_age",
        },
    );
    m.insert(
        "escrow_2party",
        VerifierSpec::StrictGroth16 {
            script: "verify_escrow_2party.js",
            prefix: "covex_escrow",
        },
    );

    m
}

/// Check for presence of a Groth16 snarkjs proof body (pi_a / A fields).
/// NOTE: this is a SHAPE check only - it does NOT verify the proof. It must
/// never gate a signing decision on its own (a planted `{"pi_a":[...]}` key
/// passes it); use circuit_requires_crypto_proof + a real verifier result.
pub fn proof_has_groth16_body(proof: &Value) -> bool {
    proof.get("pi_a").is_some() || proof.get("A").is_some()
}

/// True ONLY if the circuit's registered verifier performs REAL cryptographic
/// verification (Strict or Hybrid Groth16). For these a `true` from
/// verify_proof_for_circuit means snarkjs actually checked a proof, so an oracle
/// signature is warranted (outcome derived from the verified public signals).
///
/// Attested / Risc0Stub / WasmStub circuits do NO cryptographic check - a `true`
/// from them means only "attested", so they must NEVER mint a signature off a
/// caller-chosen requested_outcome. Only a server-resolved game outcome may.
/// This is the gate that closes the junk-`pi_a`-body free-signature bypass on
/// BOTH the off-chain (oracle.rs) and on-chain (oracle_payout_handler) paths.
pub(crate) fn circuit_requires_crypto_proof(circuit_type: &str) -> bool {
    matches!(
        get_registry().get(circuit_type),
        Some(VerifierSpec::StrictGroth16 { .. }) | Some(VerifierSpec::HybridGroth16 { .. })
    )
}

/// Consolidated node binary selection (same heuristics as legacy oracle.rs for compat).
fn node_binary() -> &'static str {
    if std::path::Path::new("/usr/bin/node").exists() {
        "/usr/bin/node"
    } else if std::path::Path::new("/root/.nvm/versions/node/v20.20.2/bin/node").exists() {
        "/root/.nvm/versions/node/v20.20.2/bin/node"
    } else {
        "node"
    }
}

/// Build path to a zk/ verifier script relative to CARGO_MANIFEST_DIR (backend/).
fn zk_script_path(rel: &str) -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("../zk");
    p.push(rel);
    p
}

/// Synchronous core: write temp proof json, invoke node <script> <tmp>, parse {valid: bool}.
/// Dedupes the ~8 near-identical copies that existed in oracle.rs.
fn run_groth16_verifier_sync(
    script: &PathBuf,
    tmp_prefix: &str,
    proof: &Value,
    public_inputs: &[String],
) -> Result<bool, String> {
    let proof_json = serde_json::json!({
        "proof": proof,
        "publicSignals": public_inputs,
    });
    let tmp_path =
        std::env::temp_dir().join(format!("{}_{}.json", tmp_prefix, uuid::Uuid::new_v4()));
    std::fs::write(
        &tmp_path,
        serde_json::to_string(&proof_json).map_err(|e| e.to_string())?,
    )
    .map_err(|e| format!("Failed to write temp proof: {}", e))?;

    // Spawn with a wall-clock timeout so a hung or malicious verifier can never hold a
    // spawn_blocking thread forever (a self-inflicted DoS). On timeout we kill the child and
    // fail closed: the oracle refuses to sign when verification does not complete in time.
    const VERIFY_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(20);
    let mut child = Command::new(node_binary())
        .arg(script.to_str().unwrap_or("zk/verify.js"))
        .arg(&tmp_path)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .map_err(|e| {
            format!(
                "Failed to run verifier (node={} script={:?}): {}",
                node_binary(),
                script,
                e
            )
        })?;

    let started = std::time::Instant::now();
    let status = loop {
        match child.try_wait() {
            Ok(Some(st)) => break st,
            Ok(None) => {
                if started.elapsed() >= VERIFY_TIMEOUT {
                    let _ = child.kill();
                    let _ = child.wait();
                    let _ = std::fs::remove_file(&tmp_path);
                    return Err(format!(
                        "Verifier timed out after {}s and was killed",
                        VERIFY_TIMEOUT.as_secs()
                    ));
                }
                std::thread::sleep(std::time::Duration::from_millis(40));
            }
            Err(e) => {
                let _ = std::fs::remove_file(&tmp_path);
                return Err(format!("Verifier wait failed: {}", e));
            }
        }
    };

    let mut stdout = String::new();
    let mut stderr = String::new();
    {
        use std::io::Read as _;
        if let Some(mut o) = child.stdout.take() {
            let _ = o.read_to_string(&mut stdout);
        }
        if let Some(mut e) = child.stderr.take() {
            let _ = e.read_to_string(&mut stderr);
        }
    }
    let _ = std::fs::remove_file(&tmp_path);

    if !status.success() {
        return Err(format!(
            "Verifier exited {}: stdout={} stderr={}",
            status,
            stdout.trim(),
            stderr.trim()
        ));
    }

    if stdout.trim().is_empty() {
        return Err(format!(
            "Verifier produced no output. stderr: {}",
            stderr.trim()
        ));
    }

    let result: Value = serde_json::from_str(&stdout)
        .map_err(|e| format!("Invalid verifier output '{}': {}", stdout.trim(), e))?;

    match result["valid"].as_bool() {
        Some(v) => Ok(v),
        None => Err(format!(
            "Unexpected verifier output: {}",
            serde_json::to_string(&result).unwrap_or_default()
        )),
    }
}

/// Async wrapper (spawn_blocking) for Groth16/snarkjs verifiers.
pub(crate) async fn run_groth16_verifier_async(
    script_rel: &str,
    tmp_prefix: &'static str,
    proof: Value,
    public_inputs: Vec<String>,
) -> Result<bool, String> {
    // Cap concurrent verifications so a burst of proof submissions cannot spawn an unbounded
    // number of node child processes (each holds a blocking thread + CPU). Excess requests wait.
    static VERIFY_SEM: std::sync::OnceLock<tokio::sync::Semaphore> = std::sync::OnceLock::new();
    let _permit = VERIFY_SEM
        .get_or_init(|| tokio::sync::Semaphore::new(6))
        .acquire()
        .await
        .map_err(|e| format!("verify semaphore closed: {}", e))?;
    let script = zk_script_path(script_rel);
    tokio::task::spawn_blocking(move || {
        run_groth16_verifier_sync(&script, tmp_prefix, &proof, &public_inputs)
    })
    .await
    .map_err(|e| format!("Spawn blocking failed: {}", e))?
}

/// Hybrid: if the proof contains a real Groth16 body, run verifier; else accept (attested path).
pub(crate) async fn run_hybrid_groth16_async(
    script_rel: &str,
    prefix: &'static str,
    proof: Value,
    public_inputs: Vec<String>,
) -> Result<bool, String> {
    if proof_has_groth16_body(&proof) {
        run_groth16_verifier_async(script_rel, prefix, proof, public_inputs).await
    } else {
        // FAIL CLOSED. A Hybrid circuit with NO proof body is not cryptographically
        // verified. The old Ok(true) soft-pass let a bodyless request through, which
        // the on-chain oracle payout would trust as "verified". Reject it - a real
        // Groth16 body or a server-resolved game outcome is required to sign.
        Err(format!(
            "hybrid circuit (prefix '{}') requires a Groth16 proof body; bodyless attestation is rejected",
            prefix
        ))
    }
}

/// Find risc0 binary (cli installed via rzup/cargo, or in common paths).
/// Returns Some(cmd) that can be invoked; caller decides args.
fn find_risc0_binary() -> Option<String> {
    let candidates = [
        "/usr/bin/risc0",
        "/usr/local/bin/risc0",
        "/root/.cargo/bin/risc0",
        "/home/*/.cargo/bin/risc0", // glob not expanded here
    ];
    for c in &candidates {
        if std::path::Path::new(c).exists() {
            return Some(c.to_string());
        }
    }
    // Try PATH via Command (cheap probe)
    if let Ok(out) = Command::new("risc0").arg("--version").output() {
        if out.status.success() {
            return Some("risc0".to_string());
        }
    }
    if let Ok(out) = Command::new("cargo").args(["risc0", "--version"]).output() {
        if out.status.success() {
            return Some("cargo".to_string());
        }
    }
    None
}

/// RISC0 stub verifier (vision Phase 0 + §4.6).
/// - If binary available: attempt a verify invocation (illustrative args; real receipt format TBD).
/// - Else (or on failure): accept. This lets "risc0_*" and "verifiable" circuits work immediately
///   as oracle-attested / hybrid until full guest receipts + verifier integration.
pub(crate) async fn verify_risc0_stub(
    guest: &str,
    _proof: Value,
    _public_inputs: Vec<String>,
    _requested_outcome: Option<u32>,
) -> Result<bool, String> {
    // Fail closed by default. There is NO real RISC0 receipt verifier implemented
    // here - the paths below only probe for a binary/receipt FILE, they never
    // cryptographically verify a receipt. Rubber-stamping a "verifiable compute"
    // outcome as proven would be dishonest, so by default we REJECT. An operator can
    // opt back into the permissive dev/testnet behavior with
    // COVEX_ALLOW_STUB_VERIFIERS=true. Mainnet must never set that flag.
    if std::env::var("COVEX_ALLOW_STUB_VERIFIERS").as_deref() != Ok("true") {
        return Err(format!(
            "RISC0 verifier for guest '{}' is not implemented; refusing to attest (set COVEX_ALLOW_STUB_VERIFIERS=true to allow attested stubs on testnet)",
            guest
        ));
    }
    let bin_opt = find_risc0_binary();
    // Sprint 2/3: Support dev guests by loading their _proof.json as receipt.
    // This makes risc0_chess_eval, risc0_poker_solver, financial_formula, etc. "use" the existing artifacts
    // instead of pure always-accept. For "real" RISC0, when risc0 binary present, we exec the guest
    // with the receipt (basic support added here for compatibility + real path).
    let guest_receipt = format!("../zk/risc0_guests/{}_proof.json", guest);
    if std::path::Path::new(&guest_receipt).exists() {
        let bin_opt = find_risc0_binary();
        if bin_opt.is_some() {
            // Real risc0 path: in full impl we'd call the binary with receipt and check output.
            // For now, if binary present and receipt exists, treat as "real verified" for dev.
            return Ok(true);
        }
        return Ok(true);
    }

    if bin_opt.is_none() {
        // No risc0 yet - stub accepts (common for dev, attested compute, or when offloading to external prover).
        return Ok(true);
    }
    let bin = bin_opt.unwrap();
    let guest = guest.to_string(); // own it so it can be moved into 'static spawn_blocking closure

    // Run in blocking task. We don't yet have standardized receipt layout in the OracleVerifyInput,
    // so this is a no-op probe for now. Future: serialize _proof as receipt.json, feed --receipt,
    // parse exit/output for validity.
    let success = tokio::task::spawn_blocking(move || {
        let mut cmd = if bin == "cargo" {
            let mut c = Command::new("cargo");
            c.args(["risc0", "verify", "--guest", &guest]);
            c
        } else {
            let mut c = Command::new(&bin);
            c.arg("verify").arg("--guest").arg(&guest);
            c
        };
        // In real use: .arg("--receipt").arg(tmp) etc.
        // For stub we fire-and-forget and accept.
        let _ = cmd.output();
        true
    })
    .await
    // Fail closed on a JoinError (the verification task panicked): a panicked verification must
    // NOT read as "verified". This is defense-in-depth only: Risc0Stub is excluded from
    // circuit_requires_crypto_proof, so a true verdict here can never mint a money signature on
    // its own (the oracle gate refuses to sign for non-crypto circuits off a caller outcome).
    .unwrap_or(false);

    Ok(success)
}

/// Locate a WASM runtime for exec verification stub.
fn find_wasm_runtime() -> Option<&'static str> {
    if std::path::Path::new("/usr/bin/wasmtime").exists() {
        return Some("/usr/bin/wasmtime");
    }
    if Command::new("wasmtime")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
    {
        return Some("wasmtime");
    }
    // Fallback: node can execute .wasm in some cases (or use for js-wasm harness)
    if std::path::Path::new("/usr/bin/node").exists()
        || std::path::Path::new("/root/.nvm/versions/node/v20.20.2/bin/node").exists()
    {
        return Some("node");
    }
    None
}

/// WASM execution / predicate stub (vision §4.6, §6).
/// Similar philosophy to RISC0: runtime if present (for future real proof-of-execution),
/// otherwise accept so wasm_* and custom WASM predicates "just work" as attested.
pub(crate) async fn verify_wasm_exec_stub(
    module_hint: &str,
    _proof: Value,
    _public_inputs: Vec<String>,
    _requested_outcome: Option<u32>,
) -> Result<bool, String> {
    // Fail closed by default - same rationale as verify_risc0_stub: this is a probe,
    // not a real proof-of-execution verifier, so we must not attest by default.
    if std::env::var("COVEX_ALLOW_STUB_VERIFIERS").as_deref() != Ok("true") {
        return Err(format!(
            "WASM verifier (module '{}') is not implemented; refusing to attest (set COVEX_ALLOW_STUB_VERIFIERS=true to allow attested stubs on testnet)",
            module_hint
        ));
    }
    let rt = find_wasm_runtime();
    if rt.is_none() {
        return Ok(true);
    }
    let rt = rt.unwrap();

    let _ = tokio::task::spawn_blocking(move || {
        // Stub invocation. Real: would validate a WASM receipt / trace / input+output commitment.
        // e.g. wasmtime run --env ... or node -e 'WebAssembly.instantiate...'
        if rt == "node" {
            let _ = Command::new(rt).args(["--version"]).output();
        } else {
            let _ = Command::new(rt).arg("--version").output();
        }
        true
    })
    .await;

    // Always accept in current stub (module_hint can be used later for allow-list or specific harness).
    let _ = module_hint;
    Ok(true)
}

/// Primary entrypoint for pluggable verification.
/// Called by oracle handler (after special pre-checks like privacy nullifier).
/// Returns Ok(true) for attested paths (caller still requires requested_outcome for pure attested
/// in the legacy "other" path; we keep that policy in oracle.rs for now).
pub(crate) async fn verify_proof_for_circuit(
    circuit_type: &str,
    proof: Value,
    public_inputs: Vec<String>,
    requested_outcome: Option<u32>,
) -> Result<bool, String> {
    let reg = get_registry();
    match reg.get(circuit_type) {
        Some(VerifierSpec::StrictGroth16 { script, prefix }) => {
            run_groth16_verifier_async(script, prefix, proof, public_inputs).await
        }
        Some(VerifierSpec::HybridGroth16 { script, prefix }) => {
            run_hybrid_groth16_async(script, prefix, proof, public_inputs).await
        }
        Some(VerifierSpec::Risc0Stub { guest }) => {
            // Sprint 1 improvement: Attempt real RISC0 execution if a guest binary is present
            // (e.g. risc0 build output). Falls back to stub for dev.
            verify_risc0_stub(guest, proof, public_inputs, requested_outcome).await
        }
        Some(VerifierSpec::WasmStub { module_hint }) => {
            verify_wasm_exec_stub(module_hint, proof, public_inputs, requested_outcome).await
        }
        Some(VerifierSpec::Attested) => {
            // Deliberate oracle-attested model (games, data feeds, property proofs):
            // verification "succeeds" and the outcome is driven by requested_outcome
            // (enforced in the oracle handler). This is an intentional, registered path.
            Ok(true)
        }
        Some(VerifierSpec::SourceOnlyNoZkey { reason }) => {
            // FAIL CLOSED. The circuit has source + a verify script + a served vkey, but no
            // served proving key, so no honest user can produce a proof. Refuse rather than
            // attest (this is NOT a caller-chosen-outcome path): the claim is not available
            // until a trusted setup ships the served _final.zkey.
            Err(format!(
                "circuit '{}' is not claimable yet: {}",
                circuit_type, reason
            ))
        }
        None => {
            // Fail closed: an UNKNOWN circuit_type has no registered verifier, so we
            // must NOT silently attest it. Returning Err makes the caller
            // (verify_and_sign_handler, which does .unwrap_or(false)) reject the request.
            Err(format!(
                "Unknown circuit_type '{}': no verifier registered (rejected)",
                circuit_type
            ))
        }
    }
}

/// Dynamic outcome determination (replaces the giant else-if chain).
///
/// FAIL-CLOSED INTRINSIC (GAP 12): for a circuit backed by a real cryptographic verifier
/// (Strict/Hybrid Groth16) the outcome is ALWAYS derived from the COMPUTED validity public signal
/// and the caller-supplied `requested_outcome` is IGNORED. Previously this function returned
/// `requested_outcome` verbatim for any circuit, and the fail-closed property lived ONLY in the
/// caller (oracle.rs) remembering to pass `None` on the verified-proof path. That made it one
/// careless future caller away from a free-outcome hole (pass `Some(0)` for a Strict circuit whose
/// proof carries valid==0 and the pot drains). Reading the signal here, unconditionally for
/// Strict/Hybrid, makes the gate intrinsic to the function: no caller can reintroduce the hole.
///
/// Game-attested behavior is UNCHANGED: game pots (chess/tictactoe/connect4) resolve their outcome
/// from the SERVER-recorded result in the oracle handlers (oracle.rs game_row / covenant_builder
/// game_pot_outcome) and never reach the `requested_outcome` branch below for their payout. The
/// tictactoe/connect4 winner is still read from publicSignals[4] in the signal-derivation section.
///
/// For circuits with NO registered crypto verifier (attested / unknown), `requested_outcome` is
/// still honored when supplied (the attested model is gated upstream by circuit_requires_crypto_proof
/// in both oracle handlers, which refuse to sign an attested non-game payout at all).
pub(crate) fn determine_outcome_for_circuit(
    circuit_type: &str,
    proof: &Value,
    public_inputs: &[String],
    requested_outcome: Option<u32>,
) -> u32 {
    // Use registry to decide whether the circuit's outcome is a COMPUTED validity signal. This
    // covers the crypto-proof circuits (Strict/Hybrid) and the SourceOnlyNoZkey DeFi circuits: the
    // latter never reach here in production (verify_proof_for_circuit fails closed before signing),
    // but we keep the same fail-closed signal-reading so a valid==0 proof can never yield outcome 0
    // if they are ever promoted back or reached defensively.
    let reg = get_registry();
    let spec = reg.get(circuit_type);
    let reads_validity_signal = matches!(
        spec,
        Some(VerifierSpec::StrictGroth16 { .. })
            | Some(VerifierSpec::HybridGroth16 { .. })
            | Some(VerifierSpec::SourceOnlyNoZkey { .. })
    );

    // requested_outcome is honored ONLY for circuits that do NOT read a validity signal (attested /
    // unknown). For Strict/Hybrid the requested value is IGNORED and we fall through to the
    // unconditional signal-reading below, so a future caller passing Some(_) cannot mint a free
    // outcome. tictactoe/connect4/privacy_mixer are Strict/Hybrid, so their requested-outcome clamp
    // is gone (their production outcome is the server game result or the verified signal, not a
    // caller value).
    if !reads_validity_signal {
        if let Some(req) = requested_outcome {
            return req;
        }
        return 0;
    }

    // Derivations for the wired full-zk / hybrid circuits (exact same logic as legacy).
    if circuit_type == "merkle_membership" || circuit_type.contains("merkle_") {
        if !public_inputs.is_empty() && public_inputs[0] == "1" {
            0
        } else {
            1
        }
    } else if circuit_type.contains("range") {
        if public_inputs.first().map(|s| s.as_str()) == Some("1") {
            0
        } else {
            1
        }
    } else if matches!(
        circuit_type,
        "age_verification" | "age_verify_v1" | "escrow_2party" | "hash_preimage"
            | "timelock_absolute" | "timelock_abs" | "relative_timelock"
            | "turn_timer" | "pot_split_math" | "vrf_random" | "script_constraint"
            | "utxo_ownership" | "basic_utxo_ownership"
            // The 5 circuits added 2026-06-18 also EXPOSE valid at publicSignals[0]. The three
            // predicate circuits (balance_threshold, solvency_sum, set_non_membership) MUST read
            // it (a below-threshold / not-bracketed proof carries valid==0 and must FAIL the
            // gate); commitment_open + anon_membership_nullifier emit valid==1 by construction,
            // so reading [0]==1 is correct and harmless. Without this they fell through to the
            // proof-presence branch below and a valid==0 proof drained the pot.
            | "commitment_open" | "balance_threshold" | "solvency_sum"
            | "set_non_membership" | "anon_membership_nullifier"
            // New 2026-06-28 primitives also EXPOSE the computed validity at publicSignals[0]:
            // merkle_range_membership = member * (value>=lo) * (value<=hi);
            // equality_of_commitments = (A opens to value) * (B opens to same value). A verifying
            // proof can carry valid==0 (out-of-band value / mismatched commitment), which MUST
            // fail the gate, so we read [0] rather than treating proof presence as success.
            | "merkle_range_membership" | "equality_of_commitments"
            // circomwave 2026-06-28 primitives, valid at publicSignals[0]:
            // nullifier_uniqueness = fresh nullifier bracketed in the spent-set;
            // threshold_sig_knowledge = held shares reconstruct the committed group secret;
            // pedersen_open_equals = committed value == public expected.
            // (merkle_multi_membership + sorted_merkle_range contain "merkle_" so they already hit
            // the merkle branch above, which reads [0] with identical semantics; listed here in a
            // comment for completeness.) A verifying proof can carry valid==0 (spent nullifier,
            // mismatched shares, value != expected), which MUST fail the gate, so we read [0].
            | "nullifier_uniqueness" | "threshold_sig_knowledge" | "pedersen_open_equals"
    ) || circuit_type.contains("timelock")
    {
        // These circuits EXPOSE their gating result as publicSignals[0]
        // (valid / on_time / ok), which is a COMPUTED output of the circuit, not a free
        // input. A verifying proof can legitimately carry [0] = 0 (e.g. age < threshold,
        // timeout not elapsed, move late), so we MUST read it: claimant wins (outcome 0)
        // ONLY when [0] == "1", otherwise the claim fails (outcome 1). This closes the
        // bug where the generic proof_has_groth16_body => 0 fallback below treated mere
        // proof presence as success and let a valid-but-false proof (e.g. an underage
        // age proof) pass the gate. Circuits with no separate valid output (nullifier_set,
        // vrf_dice_roll) intentionally fall through to the proof-presence branch.
        if public_inputs.first().map(|s| s.as_str()) == Some("1") {
            0
        } else {
            1
        }
    } else if matches!(
        circuit_type,
        "collateral_ltv" | "loan_health" | "financial_formula" | "auction_clearing"
    ) {
        // These DeFi/market circuits emit [computed_value, valid] - the gating result
        // is the SECOND public signal (publicSignals[1]), not the first. A real, verifying
        // proof can legitimately carry valid == "0" (e.g. an under-collateralized LTV, an
        // unhealthy loan, a formula that evaluates false, an auction that did not clear),
        // and that case MUST fail the gate. Reading index [1]: claimant wins (outcome 0)
        // ONLY when the validity signal equals "1", otherwise the claim fails (outcome 1).
        // Before this, they fell through to the proof_has_groth16_body => 0 fallback below,
        // so MERE proof presence let a valid-but-false proof drain the pot.
        if public_inputs.get(1).map(|s| s.as_str()) == Some("1") {
            0
        } else {
            1
        }
    } else if proof_has_groth16_body(proof) {
        0
    } else if circuit_type == "tictactoe_v1" || circuit_type == "connect4_v1" {
        if proof_has_groth16_body(proof) && public_inputs.len() >= 5 {
            match public_inputs[4].as_str() {
                "1" => 0,
                "2" => 1,
                "3" => 2,
                _ => 2,
            }
        } else {
            0
        }
    } else if circuit_type.contains("timelock") {
        if public_inputs.first().map(|s| s.as_str()) == Some("1") {
            0
        } else {
            1
        }
    } else if circuit_type == "hash_preimage" {
        if public_inputs.first().map(|s| s.as_str()) == Some("1") {
            0
        } else {
            1
        }
    } else {
        0
    }
}

/// Convenience: return a sorted list of all circuit types known to the registry.
/// Useful for diagnostics, /oracle/status, or future registry export.
// Diagnostic helper not wired to a live endpoint yet.
#[allow(dead_code)]
pub(crate) fn list_all_registered_circuit_types() -> Vec<&'static str> {
    let mut v: Vec<_> = get_registry().keys().copied().collect();
    v.sort();
    v
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_contains_core_full_zk_and_stubs() {
        let r = get_registry();
        assert!(matches!(
            r.get("merkle_membership"),
            Some(VerifierSpec::StrictGroth16 { .. })
        ));
        assert!(matches!(
            r.get("range_proof"),
            Some(VerifierSpec::StrictGroth16 { .. })
        ));
        // chess_v1 assert removed (circuit deleted)
        // privacy_mixer_v1 was removed (legal / sanctions posture): it must NOT be registered, so
        // it fails closed as an unknown circuit instead of being co-signable.
        assert!(
            r.get("privacy_mixer_v1").is_none(),
            "privacy_mixer_v1 must not be a registered verifier (removed for legal posture)"
        );
        assert!(matches!(
            r.get("verifiable"),
            Some(VerifierSpec::Risc0Stub { .. })
        ));
        assert!(matches!(
            r.get("wasm_execution"),
            Some(VerifierSpec::WasmStub { .. })
        ));
        // utxo_ownership is the catalog alias for basic_utxo_ownership: now StrictGroth16
        // (fail-closed Poseidon-note proof with a working in-browser prover + served vkey).
        assert!(matches!(
            r.get("utxo_ownership"),
            Some(VerifierSpec::StrictGroth16 { .. })
        ));
        assert!(matches!(
            r.get("liquidation_threshold"),
            Some(VerifierSpec::Attested)
        ));
        assert!(matches!(r.get("price_kas"), Some(VerifierSpec::Attested)));
        assert!(matches!(r.get("custom"), Some(VerifierSpec::Attested)));
        // Promoted to StrictGroth16 after a live trusted setup + verified proofs.
        assert!(matches!(
            r.get("relative_timelock"),
            Some(VerifierSpec::StrictGroth16 { .. })
        ));
        assert!(matches!(
            r.get("basic_utxo_ownership"),
            Some(VerifierSpec::StrictGroth16 { .. })
        ));
        assert!(matches!(
            r.get("nullifier_set"),
            Some(VerifierSpec::StrictGroth16 { .. })
        ));
        // New privacy / identity / solvency circuits, node-verified (accept + tamper + replay) before
        // registration. StrictGroth16: real proof required, bodyless request rejected.
        for id in &[
            "commitment_open",
            "balance_threshold",
            "solvency_sum",
            "set_non_membership",
            "anon_membership_nullifier",
            // New self-contained primitives (zkwave 2026-06-28), node-verified accept + tamper +
            // negative-predicate (valid==0) before registration.
            "merkle_range_membership",
            "equality_of_commitments",
            // circomwave 2026-06-28 primitives, node-verified accept + tamper + false-predicate
            // (valid==0) before registration. merkle_multi_membership was promoted out of the
            // attested crypto-primitive stub list (must not be re-attested by a later loop).
            "merkle_multi_membership",
            "nullifier_uniqueness",
            "threshold_sig_knowledge",
            "pedersen_open_equals",
            "sorted_merkle_range",
        ] {
            assert!(
                matches!(r.get(*id), Some(VerifierSpec::StrictGroth16 { .. })),
                "{} must be StrictGroth16 (not overwritten by an attested loop)",
                id
            );
        }
        // Re-pinned Strict after the attested-loop overwrite bug.
        assert!(matches!(
            r.get("escrow_2party"),
            Some(VerifierSpec::StrictGroth16 { .. })
        ));
        assert!(matches!(
            r.get("age_verification"),
            Some(VerifierSpec::StrictGroth16 { .. })
        ));
        assert!(matches!(
            r.get("vrf_card_deal"),
            Some(VerifierSpec::Attested)
        ));
        assert!(matches!(
            r.get("black_scholes"),
            Some(VerifierSpec::Attested)
        ));
        // chess_engine assert removed (circuit deleted)
    }

    /// HONESTY: the Tier-1 DeFi circuits with no served _final.zkey must NOT be presented as
    /// Groth16-claimable. They are SourceOnlyNoZkey (circuit_requires_crypto_proof == false, so
    /// the oracle never signs their outcome), and verify_proof_for_circuit must FAIL CLOSED for
    /// them (not attest a caller-chosen outcome). multi_sig_gating + anon_credential stay
    /// Attested (their circom now exists, but no served zkey, so still not claimable).
    #[tokio::test]
    async fn defi_circuits_without_served_zkey_are_not_claimable() {
        let r = get_registry();
        for id in &["collateral_ltv", "loan_health", "financial_formula"] {
            assert!(
                matches!(r.get(*id), Some(VerifierSpec::SourceOnlyNoZkey { .. })),
                "{} must be SourceOnlyNoZkey (no served proving key), not Groth16-claimable",
                id
            );
            assert!(
                !circuit_requires_crypto_proof(id),
                "{} must NOT be presented as a crypto-proof (claimable) circuit",
                id
            );
            // verify_proof_for_circuit fails closed even with a planted proof body.
            let proof = serde_json::json!({ "pi_a": ["1", "2", "3"] });
            let res = verify_proof_for_circuit(id, proof, vec!["1".to_string()], Some(0)).await;
            assert!(
                res.is_err(),
                "{} must fail closed (not claimable yet), got: {:?}",
                id,
                res
            );
        }
        // multi_sig_gating + anon_credential: circom exists now, but no served zkey -> stay
        // Attested (oracle refuses to sign their outcome) and NOT crypto-proof claimable.
        for id in &["multi_sig_gating", "anon_credential"] {
            assert!(
                matches!(r.get(*id), Some(VerifierSpec::Attested)),
                "{} must remain Attested (circom exists but no served zkey)",
                id
            );
            assert!(
                !circuit_requires_crypto_proof(id),
                "{} must NOT be presented as a crypto-proof (claimable) circuit",
                id
            );
        }
    }

    #[test]
    fn registry_has_many_vision_expansions() {
        let r = get_registry();
        // spot check breadth (ownership, vrf, defi, compute, data, gating)
        for id in &[
            "utxo_spend_auth",
            "script_constraint_proof",
            "fee_pot_math",
            "selected_parent_proof",
            "vrf_dice_roll",
            "distributed_randomness",
            "insurance_parametric",
            "amm_invariant_proof",
            "portfolio_var",
            "monte_carlo_sim",
            "regex_string_match",
            "supply_chain_graph",
            "nft_gating",
            "anti_sybil_proof",
            "price_gold",
            "drand_beacon",
            "ai_model_output",
        ] {
            assert!(r.contains_key(*id), "missing vision circuit stub: {}", id);
        }
    }

    #[test]
    fn outcome_defaults_and_clamp() {
        // An UNKNOWN circuit (no registered crypto verifier) still honors requested_outcome.
        assert_eq!(
            determine_outcome_for_circuit("foo", &Value::Null, &[], Some(5)),
            5
        );
        // chess_v1 outcome tests removed (circuit deleted)
        // privacy_mixer_v1 was removed: it is no longer a registered circuit, so the real
        // fail-closed gate is that verify_proof_for_circuit returns the unknown-circuit branch
        // and the handler refuses to sign before any outcome is computed.
        assert!(
            get_registry().get("privacy_mixer_v1").is_none(),
            "privacy_mixer_v1 must be unregistered so verify-and-sign fails closed for it"
        );
        // An unknown circuit with no requested outcome defaults to 0.
        assert_eq!(
            determine_outcome_for_circuit("some_new_defi", &Value::Null, &[], None),
            0
        );
    }

    /// GAP 12 (fail-closed intrinsic): a Strict/Hybrid circuit whose verified proof carries
    /// validity==0 MUST yield a FAIL (outcome 1), even if the caller passes requested_outcome=0
    /// ("claimant wins"). Before this fix, determine_outcome_for_circuit returned requested_outcome
    /// verbatim, so the fail-closed property lived only in the caller passing None; a future caller
    /// passing Some(0) for a below-threshold proof would have minted a winning outcome and drained
    /// the pot. The function now ignores requested_outcome for Strict/Hybrid and reads the signal.
    #[test]
    fn strict_circuit_ignores_requested_outcome_and_reads_validity() {
        let proof = serde_json::json!({ "pi_a": ["1", "2", "3"] });

        // age_verification (StrictGroth16): publicSignals[0] = valid. valid==0 (underage) with a
        // hostile requested_outcome=0 must STILL fail closed to outcome 1.
        assert_eq!(
            determine_outcome_for_circuit(
                "age_verification",
                &proof,
                &["0".to_string(), "commitment".to_string()],
                Some(0),
            ),
            1,
            "validity==0 must fail closed even when the caller requests outcome 0"
        );
        // valid==1 with a hostile requested_outcome=1 ("claim fails") must STILL read the signal
        // and yield outcome 0 (claimant wins) - the caller value is ignored both ways.
        assert_eq!(
            determine_outcome_for_circuit(
                "age_verification",
                &proof,
                &["1".to_string(), "commitment".to_string()],
                Some(1),
            ),
            0,
            "validity==1 must yield outcome 0 regardless of the requested outcome"
        );
        // A second Strict circuit (escrow_2party): same intrinsic behavior, requested ignored.
        assert_eq!(
            determine_outcome_for_circuit("escrow_2party", &proof, &["0".to_string()], Some(0)),
            1,
            "escrow_2party validity==0 must fail closed even with requested_outcome=0"
        );
    }

    #[test]
    fn valid_gated_circuits_read_public_output_not_proof_presence() {
        // A proof WITH a groth16 body. The old generic `proof_has_groth16_body => 0` fallback
        // signed "claimant wins" on mere presence; these circuits must instead read the COMPUTED
        // gating output at publicSignals[0] (valid / on_time), so a valid-but-false proof loses.
        let proof = serde_json::json!({ "pi_a": ["1", "2", "3"] });
        // age_verification [valid, commitment, ...]: valid=0 (underage) must FAIL the gate (outcome 1).
        assert_eq!(
            determine_outcome_for_circuit(
                "age_verification",
                &proof,
                &["0".to_string(), "x".to_string()],
                None
            ),
            1
        );
        assert_eq!(
            determine_outcome_for_circuit(
                "age_verification",
                &proof,
                &["1".to_string(), "x".to_string()],
                None
            ),
            0
        );
        // escrow_2party [valid, ...]: valid=0 (timeout not elapsed) -> claim fails.
        assert_eq!(
            determine_outcome_for_circuit("escrow_2party", &proof, &["0".to_string()], None),
            1
        );
        assert_eq!(
            determine_outcome_for_circuit("escrow_2party", &proof, &["1".to_string()], None),
            0
        );
        // timelocks [valid, ...] and turn_timer [on_time, ...]: read the public output.
        assert_eq!(
            determine_outcome_for_circuit("timelock_absolute", &proof, &["0".to_string()], None),
            1
        );
        assert_eq!(
            determine_outcome_for_circuit("relative_timelock", &proof, &["1".to_string()], None),
            0
        );
        assert_eq!(
            determine_outcome_for_circuit("turn_timer", &proof, &["0".to_string()], None),
            1
        );
        // Circuits with NO separate valid output keep proof-presence => 0 (a verifying proof IS
        // the claim): nullifier_set [spent=0, ...] and vrf_dice_roll [seed, roll].
        assert_eq!(
            determine_outcome_for_circuit(
                "nullifier_set",
                &proof,
                &["0".to_string(), "n".to_string()],
                None
            ),
            0
        );
        assert_eq!(
            determine_outcome_for_circuit(
                "vrf_dice_roll",
                &proof,
                &["999".to_string(), "3".to_string()],
                None
            ),
            0
        );
    }

    /// circomwave 2026-06-28 primitives: each EXPOSES its computed validity at publicSignals[0]
    /// (valid = a CONSTRAINED product of comparator/equality outputs, never a free input). A
    /// verifying proof can legitimately carry valid==0 (a leaf outside the set, a spent nullifier,
    /// mismatched shares, value != expected, an out-of-order sorted value), which MUST fail the
    /// gate. This asserts the Rust outcome reads the signal: valid==1 -> claimant wins (outcome 0),
    /// valid==0 -> claim fails (outcome 1), and a missing signal fails closed. These are the same
    /// circuits proven end-to-end off-chain (accept + tamper-reject + false-predicate valid==0)
    /// before they were registered StrictGroth16.
    #[test]
    fn circomwave_primitives_read_validity_signal_not_proof_presence() {
        // A proof WITH a groth16 body, so we prove the outcome reads the COMPUTED signal, not
        // mere proof presence (the old generic `proof_has_groth16_body => 0` drain).
        let proof = serde_json::json!({ "pi_a": ["1", "2", "3"] });
        for circuit in [
            "merkle_multi_membership",
            "nullifier_uniqueness",
            "threshold_sig_knowledge",
            "pedersen_open_equals",
            "sorted_merkle_range",
        ] {
            // valid == "1" at publicSignals[0] -> claimant wins (outcome 0).
            assert_eq!(
                determine_outcome_for_circuit(circuit, &proof, &["1".to_string()], None),
                0,
                "{circuit}: valid==1 at [0] must yield outcome 0 (claimant wins)"
            );
            // valid == "0" at publicSignals[0] -> claim fails (outcome 1), even with a proof body.
            // This is the false-predicate case (a real verifying proof carrying valid==0) that
            // MUST NOT drain the pot.
            assert_eq!(
                determine_outcome_for_circuit(circuit, &proof, &["0".to_string()], None),
                1,
                "{circuit}: valid==0 at [0] (false predicate) must FAIL the gate (outcome 1)"
            );
            // A missing validity signal must fail closed (never default to a win).
            assert_eq!(
                determine_outcome_for_circuit(circuit, &proof, &[], None),
                1,
                "{circuit}: a missing validity signal must fail closed (outcome 1)"
            );
        }
    }

    #[test]
    fn defi_market_circuits_read_validity_at_index_one_not_proof_presence() {
        // collateral_ltv / loan_health / financial_formula / auction_clearing emit
        // [computed_value, valid] - the gating result is publicSignals[1], NOT [0]. Before the
        // fix these fell through to the generic `proof_has_groth16_body => 0` arm, so a real,
        // verifying proof whose validity signal was "0" (under-collateralized, unhealthy loan,
        // formula false, auction did not clear) still signed "claimant wins" and drained the pot.
        // A groth16 body is present (these are Hybrid/groth circuits in the registry), proving the
        // fix reads the signal, not mere proof presence.
        let proof = serde_json::json!({ "pi_a": ["1", "2", "3"] });
        for circuit in [
            "collateral_ltv",
            "loan_health",
            "financial_formula",
            "auction_clearing",
        ] {
            // valid == "1" at index [1] -> claimant wins (outcome 0). The value at [0] is the
            // circuit's computed quantity (e.g. LTV bps), which MUST NOT be mistaken for validity.
            assert_eq!(
                determine_outcome_for_circuit(
                    circuit,
                    &proof,
                    &["5000".to_string(), "1".to_string()],
                    None
                ),
                0,
                "{circuit}: valid==1 at [1] must yield outcome 0"
            );
            // valid == "0" at index [1] -> claim fails (outcome 1), even though [0] is non-zero
            // AND the proof body is present. This is the drain that the old fallback allowed.
            assert_eq!(
                determine_outcome_for_circuit(
                    circuit,
                    &proof,
                    &["5000".to_string(), "0".to_string()],
                    None
                ),
                1,
                "{circuit}: valid==0 at [1] must FAIL the gate (outcome 1), not pass on proof presence"
            );
            // Defensive: a malformed proof missing the validity signal must NOT default to a win.
            assert_eq!(
                determine_outcome_for_circuit(circuit, &proof, &["5000".to_string()], None),
                1,
                "{circuit}: a missing validity signal must fail closed (outcome 1)"
            );
        }
    }

    #[test]
    fn groth_body_detection() {
        let mut p = serde_json::json!({});
        assert!(!proof_has_groth16_body(&p));
        p["pi_a"] = serde_json::json!([]);
        assert!(proof_has_groth16_body(&p));
        p = serde_json::json!({"A": "x"});
        assert!(proof_has_groth16_body(&p));
    }

    #[test]
    fn risc0_and_wasm_stubs_accept_without_bin() {
        // These are sync in effect for the stub path (no bin in test env)
        let fut = verify_risc0_stub("test", Value::Null, vec![], None);
        // Can't easily await in sync test without runtime; just ensure registry + fns exist.
        // In practice tokio test would pass.
        let _ = fut; // type checks
        let _ = verify_wasm_exec_stub("hint", Value::Null, vec![], Some(0));
    }
}
