use crate::covenant_types::{UiGenerationConfig, UiParameter};

/// Basic UI for FREE/EXPLORER tier covenants.
/// Includes danger banner, limited fields (tx_id, script_hash, amount, type, timestamp only).
pub fn generate_basic_ui(config: &UiGenerationConfig) -> String {
    let form_html = build_form_html(&config.parameters);
    let danger_banner = r#"<div class="danger-banner">
  <div class="danger-icon">!</div>
  <div class="danger-text">
    <strong>DANGEROUS / UNVERIFIED COVENANT</strong>
    <p>This covenant has NOT been verified by its creator via on-chain payment. Limited disclosure only. Use at your own risk.</p>
  </div>
</div>"#;

    format!(
        r#"<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>{name} | Covex (Unverified)</title>
<style>{css}</style></head><body>
  <div class="glass-panel">
    <div class="header"><h1>{name}</h1>
      <div class="badge-row"><span class="badge badge-category">{category}</span><span class="badge badge-danger">UNVERIFIED</span></div>
      <div class="script-hash">Script: {shorthash}</div>
    </div>
    {danger_banner}
    <div class="limited-disclosure">
      <h3>Limited Disclosure (FREE Tier)</h3>
      <div class="field-row"><span>TX ID</span><span class="mono-truncate">{covenant_id}</span></div>
      <div class="field-row"><span>Category</span><span>{category}</span></div>
      <div class="field-row"><span>Type</span><span>{ctype}</span></div>
      <div class="field-row"><span>Script Hash</span><span class="mono-truncate">{script_hash}</span></div>
    </div>
    <div class="disclosure-note">
      <p>Full parameter breakdown, receiving addresses, and logic summary are only available for verified (paid) covenants.</p>
      <p>The covenant creator can verify by sending the tier payment from this creator address to the Covex treasury.</p>
    </div>
    <form id="covenant-form">{form_html}
      <button type="submit" class="btn btn-primary" id="interact-btn" disabled>Connect Wallet to Interact</button>
    </form>
    <div class="error-box" id="error-box"></div><div class="success-box" id="success-box"></div>
  </div>
  <div class="footer"><p>Generated by <a href="https://github.com/THTProtocol/Covex27">Covex</a></p><p>ALL covenants are immutable on-chain. Covex only indexes and generates UIs.</p><p>Non-custodial: Keys stay in your wallet.</p></div>
{interact_script}
</body></html>"#,
        name = config.covenant_name,
        category = config.category,
        shorthash = &config.script_hash[..16.min(config.script_hash.len())],
        danger_banner = danger_banner,
        covenant_id = config.covenant_id,
        ctype = "covenant",
        script_hash = config.script_hash,
        form_html = form_html,
        css = UI_CSS,
        interact_script = INTERACT_SCRIPT,
    )
}

/// Enhanced UI for BUILDER/PRO/MAX tier covenants.
/// Full disclosure: all fields, logic summary, receiving addresses, verified badge, customization hooks.
pub fn generate_enhanced_ui(config: &UiGenerationConfig, verified_tier: &str) -> String {
    let form_html = build_form_html(&config.parameters);
    let verified_banner = format!(
        r#"<div class="verified-banner"><div class="verified-icon">V</div>
    <div class="verified-text"><strong>VERIFIED COVENANT</strong> ({tier} tier)<p>Full transparency. All receiving addresses, logic, and parameters disclosed.</p></div></div>"#,
        tier = verified_tier
    );
    let tier_color = match verified_tier {
        "MAX" => "#A855F7",
        "PRO" => "#E8AF34",
        _ => "#3B82F6",
    };

    format!(
        r#"<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>{name} | Covex (Verified {tier})</title>
<style>{css}
  .verified-banner{{background:rgba(16,185,129,0.06);border:1px solid rgba(16,185,129,0.25);border-radius:12px;padding:16px 20px;display:flex;align-items:center;gap:14px;margin-bottom:28px}}
  .verified-icon{{width:40px;height:40px;border-radius:12px;background:rgba(16,185,129,0.15);color:#10B981;display:flex;align-items:center;justify-content:center;font-size:20px;font-weight:800}}
  .verified-text strong{{color:#10B981;font-size:14px}}
  .verified-text p{{color:#6EE7B7;font-size:12px;margin-top:2px}}
</style></head><body>
  <div class="glass-panel" style="border-color:{tier_color};">
    <div class="header"><h1>{name}</h1>
      <div class="badge-row"><span class="badge badge-category">{category}</span><span class="badge badge-verified">{tier}</span></div>
      <div class="script-hash">Script: {shorthash}</div>
    </div>
    {verified_banner}
    <div class="full-disclosure">
      <h3>Full Disclosure ({tier} Tier) — Everything there is to know (fully transparent)</h3>
      <div class="field-row"><span>TX ID</span><span class="mono-truncate">{covenant_id}</span></div>
      <div class="field-row"><span>Category</span><span>{category}</span></div>
      <div class="field-row"><span>Script Hash</span><span class="mono-truncate">{script_hash}</span></div>
      <div class="field-row"><span>Creator (only they can set custom nice UI)</span><span class="mono-truncate">{creator}</span></div>
      <div class="field-row"><span>Receiving Addresses</span><span class="mono-truncate">{creator}</span></div>
      <div class="field-row"><span>Oracle Proof / Sig</span><span>Verified on-chain via Covex oracle (see covenant detail for sig + message)</span></div>
      <div class="field-row"><span>Logic Summary</span><span>Verified {tier} covenant. Type: p2sh-covenant. All parameters, payments, and script public. {if custom}Custom nice UI deployed by creator.{/if}</span></div>
      <div class="field-row"><span>Transparency Note</span><span>All on-chain data (script, params, treasury payment, oracle attestation) disclosed. No hidden settings for regular users. Creator-only advanced/terminal.</span></div>
    </div>
    <form id="covenant-form">{form_html}
      <button type="submit" class="btn btn-primary" id="interact-btn" disabled>Connect Wallet to Interact</button>
    </form>
    <div class="error-box" id="error-box"></div><div class="success-box" id="success-box"></div>
  </div>
  <div class="footer"><p>Generated by <a href="https://github.com/THTProtocol/Covex27">Covex</a></p><p>ALL covenants are immutable on-chain. Covex only generates UIs and provides transparency based on verified payments.</p><p>Non-custodial: Keys stay in your wallet.</p></div>
{interact_script}
</body></html>"#,
        name = config.covenant_name,
        tier = verified_tier,
        category = config.category,
        shorthash = &config.script_hash[..16.min(config.script_hash.len())],
        verified_banner = verified_banner,
        covenant_id = config.covenant_id,
        script_hash = config.script_hash,
        creator = if config.creator_addr.is_empty() {
            "N/A"
        } else {
            &config.creator_addr
        },
        form_html = form_html,
        tier_color = tier_color,
        css = UI_CSS,
        interact_script = INTERACT_SCRIPT,
    )
}

fn build_form_html(params: &[UiParameter]) -> String {
    params.iter().map(|p| {
        let req = if p.required { "required" } else { "" };
        match p.param_type.as_str() {
            "amount" => format!(r#"<div class="field"><label>{}{}</label><div class="amount-input-wrapper"><input type="number" id="{}" placeholder="{}" step="0.00000001" min="0" class="cyber-input" {}><span class="kas-suffix">KAS</span></div></div>"#, p.label, if p.required {" *"} else {""}, p.name, p.placeholder, req),
            "address" => format!(r#"<div class="field"><label>{}{}</label><input type="text" id="{}" placeholder="{}" class="cyber-input address-field" {}></div>"#, p.label, if p.required {" *"} else {""}, p.name, p.placeholder, req),
            _ => format!(r#"<div class="field"><label>{}{}</label><input type="text" id="{}" placeholder="{}" class="cyber-input" {}></div>"#, p.label, if p.required {" *"} else {""}, p.name, p.placeholder, req),
        }
    }).collect::<Vec<_>>().join("\n")
}

pub fn extract_parameters_from_script(_script_hex: &str, _script_hash: &str) -> Vec<UiParameter> {
    vec![
        UiParameter {
            name: "amount".into(),
            label: "Amount to Lock".into(),
            param_type: "amount".into(),
            required: true,
            placeholder: "Enter KAS amount...".into(),
            options: None,
            default_value: None,
        },
        UiParameter {
            name: "recipient".into(),
            label: "Recipient Address".into(),
            param_type: "address".into(),
            required: false,
            placeholder: "kaspatest:...".into(),
            options: None,
            default_value: None,
        },
    ]
}

const UI_CSS: &str = r#"*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
body{background:radial-gradient(circle at 50% 0%,#11111a 0%,#05050A 100%);background-attachment:fixed;color:#F3F4F6;font-family:Inter,system-ui,-apple-system,sans-serif;min-height:100vh;-webkit-font-smoothing:antialiased;display:flex;flex-direction:column;align-items:center;padding:40px 20px}
.glass-panel{background:rgba(255,255,255,0.02);backdrop-filter:blur(24px);border:1px solid rgba(255,255,255,0.05);box-shadow:0 8px 32px 0 rgba(0,0,0,0.4);border-radius:24px;padding:40px;width:100%;max-width:700px}
.header{text-align:center;margin-bottom:24px}
.header h1{font-size:28px;font-weight:700;color:#fff;margin-bottom:8px}
.script-hash{font-size:11px;font-family:monospace;color:#49EACB;background:rgba(73,234,203,0.08);padding:4px 12px;border-radius:9999px;display:inline-block;margin-top:4px}
.badge-row{display:flex;gap:8px;justify-content:center;margin:12px 0}
.badge{font-size:11px;font-weight:600;padding:4px 12px;border-radius:9999px;text-transform:uppercase;letter-spacing:.5px}
.badge-category{background:rgba(73,234,203,0.08);color:#49EACB;border:1px solid rgba(73,234,203,0.2)}
.badge-danger{background:rgba(239,68,68,0.08);color:#EF4444;border:1px solid rgba(239,68,68,0.25)}
.badge-verified{background:rgba(16,185,129,0.08);color:#10B981;border:1px solid rgba(16,185,129,0.25)}
.danger-banner{background:rgba(239,68,68,0.05);border:1px solid rgba(239,68,68,0.2);border-radius:14px;padding:18px 22px;display:flex;align-items:center;gap:14px;margin-bottom:28px}
.danger-icon{width:44px;height:44px;border-radius:12px;background:rgba(239,68,68,0.12);color:#EF4444;display:flex;align-items:center;justify-content:center;font-size:24px;font-weight:800;flex-shrink:0}
.danger-text strong{color:#EF4444;font-size:13px}.danger-text p{color:#FCA5A5;font-size:11px;margin-top:3px}
.limited-disclosure,.full-disclosure{margin-bottom:24px}
.limited-disclosure h3,.full-disclosure h3{font-size:13px;color:#9CA3AF;margin-bottom:12px;text-transform:uppercase;letter-spacing:1px}
.field-row{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid rgba(255,255,255,0.04);font-size:12px}
.field-row span:first-child{color:#6B7280}
.field-row span:last-child{color:#D1D5DB}
.mono-truncate{font-family:monospace;font-size:10px;max-width:300px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.disclosure-note{margin-bottom:24px;padding:12px 16px;border-radius:10px;background:rgba(245,158,11,0.05);border:1px solid rgba(245,158,11,0.15);font-size:11px;color:#FBBF24}
.disclosure-note p{margin-top:4px}
.field{margin-bottom:20px}
.field label{display:block;font-size:12px;font-weight:500;color:#9CA3AF;margin-bottom:8px;text-transform:uppercase;letter-spacing:.5px}
.cyber-input{background:rgba(0,0,0,0.4);border:1px solid rgba(73,234,203,0.2);color:#49EACB;width:100%;padding:12px 16px;border-radius:12px;font-size:16px;font-family:monospace;transition:all .3s ease}
.cyber-input:focus{outline:none;border-color:#49EACB;box-shadow:0 0 15px rgba(73,234,203,0.2)}
.cyber-input::placeholder{color:rgba(73,234,203,0.15)}
.amount-input-wrapper{position:relative}.amount-input-wrapper input{padding-right:60px}
.kas-suffix{position:absolute;right:16px;top:50%;transform:translateY(-50%);color:#49EACB;font-weight:700;font-size:14px;pointer-events:none}
.btn{width:100%;padding:16px 24px;border-radius:14px;font-size:16px;font-weight:700;cursor:pointer;transition:all .2s ease;border:none;text-transform:uppercase;letter-spacing:1px}
.btn-primary{background:#49EACB;color:#05050A}
.btn-primary:hover{filter:brightness(1.1)}
.btn-primary:disabled{opacity:.4;cursor:not-allowed}
.footer{margin-top:32px;text-align:center;font-size:11px;color:#6B7280}.footer a{color:#49EACB;text-decoration:none}.footer p{margin-top:4px}
.error-box{background:rgba(239,68,68,0.08);border:1px solid rgba(239,68,68,0.2);border-radius:12px;padding:16px;margin-top:16px;display:none;color:#EF4444;font-size:13px}
.success-box{background:rgba(16,185,129,0.08);border:1px solid rgba(16,185,129,0.2);border-radius:12px;padding:16px;margin-top:16px;display:none;color:#10B981;font-size:13px}"#;

const INTERACT_SCRIPT: &str = r#"<script>
const TREASURY="kaspatest:qpyfz03k6quxwf2jglwkhczvt758d8xrq99gl37p6h3vsqur27ltjhn68354m";
let wallet=null,address=null;
const se=id=>document.getElementById(id);
function detect(){let w=null;if(window.kasware)w='kasware';else if(window.__kaspium)w='kaspium';else if(window.$onekey?.kaspa)w='onekey';if(w){wallet=w;se('wallet-indicator')?.remove();connect();}else{se('interact-btn').textContent='Open Wallet App';se('interact-btn').disabled=false;}}
async function connect(){try{const p=wallet==='kasware'?window.kasware:wallet==='kaspium'?window.__kaspium:window.$onekey.kaspa;const a=await p.request({method:'kaspa_requestAccounts'});if(a?.[0]){address=a[0];se('interact-btn').textContent='Sign & Interact';se('interact-btn').disabled=false;}}catch(e){se('interact-btn').textContent='Open Wallet App';se('interact-btn').disabled=false;}}
se('covenant-form').addEventListener('submit',function(e){e.preventDefault();se('error-box').style.display='none';se('success-box').style.display='none';
const amt=parseFloat(se('amount')?.value||0);if(amt<=0){se('error-box').textContent='Enter a valid amount';se('error-box').style.display='block';return;}
const sompi=Math.floor(amt*1e8);
if(wallet&&address){const p=wallet==='kasware'?window.kasware:wallet==='kaspium'?window.__kaspium:window.$onekey.kaspa;
p.request({method:'kaspa_sendTransaction',params:[{to:TREASURY,amount:sompi}]}).then(()=>{se('success-box').textContent='Transaction sent!';se('success-box').style.display='block';}).catch(err=>{window.open('kaspatest:'+TREASURY.replace('kaspatest:','')+'?amount='+sompi,'_blank');});}
else{window.open('kaspatest:'+TREASURY.replace('kaspatest:','')+'?amount='+sompi,'_blank');se('success-box').textContent='Wallet app opened.';se('success-box').style.display='block';}});
detect();setInterval(detect,5000);
</script>"#;
