//! Re-exports the guest ELF and image id generated by `risc0_build::embed_methods()`.
//!
//! The generated file defines `GAMES_GUEST_ELF: &[u8]` (the RISC-V program the prover runs) and
//! `GAMES_GUEST_ID: [u32; 8]` (the image id the verifier checks the receipt against). The constant
//! names are derived from the guest binary name (`games-guest` -> `GAMES_GUEST_*`).
include!(concat!(env!("OUT_DIR"), "/methods.rs"));
