//! Re-exports the guest ELF and image id generated by `risc0_build::embed_methods()`.
//!
//! The generated file defines `COMPUTE_GUEST_ELF: &[u8]` (the RISC-V program the prover runs) and
//! `COMPUTE_GUEST_ID: [u32; 8]` (the image id the verifier checks the receipt against). The
//! constant names are derived from the guest binary name (`compute-guest` -> `COMPUTE_GUEST_*`).
include!(concat!(env!("OUT_DIR"), "/methods.rs"));
